#ifndef GUARD_CONSTANTS_FIELD_MOVE_H
#define GUARD_CONSTANTS_FIELD_MOVE_H


enum FieldMove
{
    FIELD_MOVE_CUT,
    FIELD_MOVE_FLASH,
    FIELD_MOVE_ROCK_SMASH,
    FIELD_MOVE_STRENGTH,
    FIELD_MOVE_SURF,
    FIELD_MOVE_FLY,
    FIELD_MOVE_DIVE,
    FIELD_MOVE_WATERFALL,
    FIELD_MOVE_TELEPORT,
    FIELD_MOVE_DIG,
    FIELD_MOVE_SECRET_POWER,
    FIELD_MOVE_MILK_DRINK,
    FIELD_MOVE_SOFT_BOILED,
    FIELD_MOVE_SWEET_SCENT,
#if OW_ROCK_CLIMB_FIELD_MOVE == TRUE
    FIELD_MOVE_ROCK_CLIMB,
#endif
#if OW_DEFOG_FIELD_MOVE == TRUE
    FIELD_MOVE_DEFOG,
#endif
#if OW_HAZE_FIELD_MOVE == TRUE
    FIELD_MOVE_HAZE,
#endif
#if OW_SUNNY_DAY_FIELD_MOVE == TRUE
    FIELD_MOVE_SUNNY_DAY,
#endif
#if OW_RAIN_DANCE_FIELD_MOVE == TRUE
    FIELD_MOVE_RAIN_DANCE,
#endif
#if OW_HAIL_FIELD_MOVE == TRUE
    FIELD_MOVE_HAIL,
#endif
#if OW_SANDSTORM_FIELD_MOVE == TRUE
    FIELD_MOVE_SANDSTORM,
#endif
#if OW_BOUNCE_FIELD_MOVE == TRUE
    FIELD_MOVE_BOUNCE,
#endif
    FIELD_MOVES_COUNT
};


#endif //GUARD_CONSTANTS_FIELD_MOVE_H
