gText_Birch_Welcome::
	.string "Bienvenido a POKéMON ARCADE!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Esto es un POKéMON.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Este es un juego de POKéMON\n"
	.string "competitivo estilo ARCADE.\p"
	.string "Aquí importa la estrategia: equipos,\n"
	.string "roles, sinergias y decisiones.\p"
	.string "Cada combate es un reto rápido\n"
	.string "donde eliges y peleas.\p"
	.string "Aprende a leer al rival, gestionar\n"
	.string "riesgos y mejorar cada partida.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "¿Y tú eres?$"

gText_Birch_BoyOrGirl::
	.string "¿Eres un chico?\n"
	.string "¿O eres una chica?$"

gText_Birch_WhatsYourName::
	.string "Muy bien.\n"
	.string "¿Cómo te llamas?$"

gText_Birch_SoItsPlayer::
	.string "Entonces eres {PLAYER}{KUN}, ¿no?$"

gText_Birch_YourePlayer::
	.string "¡Ah, vale!\p"
	.string "Eres {PLAYER}{KUN}, el que se muda a\n"
	.string "mi pueblo, VILLA RAÍZ.\l"
	.string "¡Ya lo entiendo!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Muy bien, ¿estás listo?\p"
	.string "Tu propia aventura está a punto\n"
	.string "de comenzar.\p"
	.string "Ármate de valor y lánzate al\n"
	.string "mundo POKéMON, donde te esperan\l"
	.string "sueños, aventuras y amistades.\p"
	.string "Bueno, te esperaré más tarde.\n"
	.string "Ven a verme a mi LABORATORIO POKéMON.\p"
	.string "$"
