	.align 2
gText_ConfirmSave::
	.string "¿Quieres guardar la partida?$"

gText_AlreadySavedFile::
	.string "Ya hay una partida guardada.\n"
	.string "¿Quieres sobrescribirla?$"

gText_SavingDontTurnOff::
	.string "GUARDANDO…\n"
	.string "NO APAGUES LA CONSOLA.$"

gText_PlayerSavedGame::
	.string "{PLAYER} guardó la partida.$"

gText_DifferentSaveFile::
	.string "¡ATENCIÓN!\p"
	.string "Hay otra partida guardada.\n"
	.string "Si guardas ahora, esa aventura,\p"
	.string "incluidos objetos y POKéMON,\l"
	.string "se perderá por completo.\p"
	.string "¿Seguro que quieres guardar ahora\n"
	.string "y sobrescribir la otra partida?$"

gText_SaveError::
	.string "Error al guardar.\p"
	.string "Cambia la memoria\n"
	.string "de respaldo.$"

gText_SavingDontTurnOffPower::
	.string "GUARDANDO…\n"
	.string "NO APAGUES LA CONSOLA.$"
