#include "global.h"
#include "strings.h"
#include "battle_pyramid_bag.h"
#include "item_menu.h"

ALIGNED(4)
const u8 gText_ExpandedPlaceholder_Empty[] = _("");
const u8 gText_ExpandedPlaceholder_Kun[] = _("");
const u8 gText_ExpandedPlaceholder_Chan[] = _("");
const u8 gText_ExpandedPlaceholder_Sapphire[] = _("SAPPHIRE");
const u8 gText_ExpandedPlaceholder_Ruby[] = _("RUBY");
const u8 gText_ExpandedPlaceholder_Emerald[] = _("EMERALD");
const u8 gText_ExpandedPlaceholder_Aqua[] = _("AQUA");
const u8 gText_ExpandedPlaceholder_Magma[] = _("MAGMA");
const u8 gText_ExpandedPlaceholder_Archie[] = _("ARCHIE");
const u8 gText_ExpandedPlaceholder_Maxie[] = _("MAXIE");
const u8 gText_ExpandedPlaceholder_Kyogre[] = _("KYOGRE");
const u8 gText_ExpandedPlaceholder_Groudon[] = _("GROUDON");
const u8 gText_ExpandedPlaceholder_Brendan[] = _("BRENDAN");
const u8 gText_ExpandedPlaceholder_May[] = _("MAY");
const u8 gText_EggNickname[POKEMON_NAME_LENGTH + 1] = _("EGG");
const u8 gText_Pokemon[POKEMON_NAME_LENGTH + 1] = _("POKéMON");
const u8 gText_Player[] = _("PLAYER"); // Unused
const u8 gText_Pokedex[] = _("POKéDEX"); // Unused
const u8 gText_Time[] = _("TIEMPO");
const u8 gText_Badges[] = _("BADGES"); // Unused
const u8 gText_AButton[] = _("A Button"); // Unused
const u8 gText_BButton[] = _("B Button"); // Unused
const u8 gText_RButton[] = _("R Button"); // Unused
const u8 gText_LButton[] = _("L Button"); // Unused
const u8 gText_Start[] = _("START"); // Unused
const u8 gText_Select[] = _("SELECT"); // Unused
const u8 gText_ControlPad[] = _("+ Control Pad"); // Unused
const u8 gText_LButtonRButton[] = _("L Button  R Button"); // Unused
const u8 gText_Controls[] = _("CONTROLS"); // Unused
ALIGNED(4) const u8 gText_PickOk[] = _("{DPAD_UPDOWN}ELIGE {A_BUTTON}OK"); // Unused
ALIGNED(4) const u8 gText_Next[] = _("{A_BUTTON}SIG."); // Unused
ALIGNED(4) const u8 gText_NextBack[] = _("{A_BUTTON}SIG. {B_BUTTON}ATRÁS"); // Unused
ALIGNED(4) const u8 gText_PickNextCancel[] = _("{DPAD_UPDOWN}ELIGE {A_BUTTON}SIG. {B_BUTTON}CANCELAR");
ALIGNED(4) const u8 gText_PickCancel[] = _("{DPAD_UPDOWN}ELIGE {A_BUTTON}{B_BUTTON}CANCELAR");
ALIGNED(4) const u8 gText_AButtonExit[] = _("{A_BUTTON}SALIR");
const u8 gText_ThisIsAPokemon[] = _("A esto lo llamamos “POKéMON.”{PAUSE 96}\p");
const u8 gText_5MarksPokemon[] = _("????? POKéMON");
const u8 gText_UnkHeight[] = _("{CLEAR_TO 0x0C}??'??”");
const u8 gText_UnkHeightMetric[] = _("???.? m");
const u8 gText_UnkWeight[] = _("????.? lbs.");
const u8 gText_UnkWeightMetric[] = _("???.? kg.");
const u8 gText_EmptyPkmnCategory[] = _("                       POKéMON"); // Unused
const u8 gText_EmptyHeight[] = _("{CLEAR_TO 0x0C}    '    ”"); // Unused
const u8 gText_EmptyWeight[] = _("        .   lbs."); // Unused
const u8 gText_EmptyPokedexInfo1[] = _(""); // Unused
const u8 gText_CryOf[] = _("CRY OF");
const u8 gText_EmptyPokedexInfo2[] = _(""); // Unused
const u8 gText_SizeComparedTo[] = _("SIZE COMPARED TO ");
const u8 gText_PokedexRegistration[] = _("Registro de la POKéDEX completado.");
const u8 gText_HTHeight[] = _("ALT");
const u8 gText_WTWeight[] = _("PESO");
const u8 gText_SearchingPleaseWait[] = _("Buscando…\nEspera un momento.");
const u8 gText_SearchCompleted[] = _("Búsqueda completada.");
const u8 gText_NoMatchingPkmnWereFound[] = _("No se han encontrado POKéMON.");
const u8 gText_SearchForPkmnBasedOnParameters[] = _("Buscar POKéMON según\nlos parámetros seleccionados.");
const u8 gText_SwitchPokedexListings[] = _("Cambiar el listado de la POKéDEX.");
const u8 gText_ReturnToPokedex[] = _("Volver a la POKéDEX.");
const u8 gText_SelectPokedexMode[] = _("Elige el modo POKéDEX.");
const u8 gText_SelectPokedexListingMode[] = _("Elige el modo de listado.");
const u8 gText_ListByFirstLetter[] = _("Listar por inicial.\nSolo POKéMON vistos.");
const u8 gText_ListByBodyColor[] = _("Listar por color.\nSolo POKéMON vistos.");
const u8 gText_ListByType[] = _("Listar por tipo.\nSolo POKéMON capturados.");
const u8 gText_ExecuteSearchSwitch[] = _("Ejecutar búsqueda/cambio.");
const u8 gText_DexHoennTitle[] = _("POKéDEX HOENN");
const u8 gText_DexNatTitle[] = _("POKéDEX NACIONAL");
const u8 gText_DexSortNumericalTitle[] = _("MODO NUMÉRICO");
const u8 gText_DexSortAtoZTitle[] = _("MODO A-Z");
const u8 gText_DexSortHeaviestTitle[] = _("MODO MÁS PESADO");
const u8 gText_DexSortLightestTitle[] = _("MODO MÁS LIGERO");
const u8 gText_DexSortTallestTitle[] = _("MODO MÁS ALTO");
const u8 gText_DexSortSmallestTitle[] = _("MODO MÁS BAJO");
const u8 gText_DexSearchAlphaABC[] = _("ABC");
const u8 gText_DexSearchAlphaDEF[] = _("DEF");
const u8 gText_DexSearchAlphaGHI[] = _("GHI");
const u8 gText_DexSearchAlphaJKL[] = _("JKL");
const u8 gText_DexSearchAlphaMNO[] = _("MNO");
const u8 gText_DexSearchAlphaPQR[] = _("PQR");
const u8 gText_DexSearchAlphaSTU[] = _("STU");
const u8 gText_DexSearchAlphaVWX[] = _("VWX");
const u8 gText_DexSearchAlphaYZ[] = _("YZ");
const u8 gText_DexSearchColorRed[] = _("ROJO");
const u8 gText_DexSearchColorBlue[] = _("AZUL");
const u8 gText_DexSearchColorYellow[] = _("AMARILLO");
const u8 gText_DexSearchColorGreen[] = _("VERDE");
const u8 gText_DexSearchColorBlack[] = _("NEGRO");
const u8 gText_DexSearchColorBrown[] = _("MARRÓN");
const u8 gText_DexSearchColorPurple[] = _("MORADO");
const u8 gText_DexSearchColorGray[] = _("GRIS");
const u8 gText_DexSearchColorWhite[] = _("BLANCO");
const u8 gText_DexSearchColorPink[] = _("ROSA");
const u8 gText_DexHoennDescription[] = _("POKéDEX de la región HOENN");
const u8 gText_DexNatDescription[] = _("POKéDEX Nacional");
const u8 gText_DexSortNumericalDescription[] = _("POKéMON ordenados por número.");
const u8 gText_DexSortAtoZDescription[] = _("POKéMON vistos y capturados\nen orden alfabético.");
const u8 gText_DexSortHeaviestDescription[] = _("POKéMON capturados del más\npesado al más ligero.");
const u8 gText_DexSortLightestDescription[] = _("POKéMON capturados del más\nligero al más pesado.");
const u8 gText_DexSortTallestDescription[] = _("POKéMON capturados del más\nalto al más bajo.");
const u8 gText_DexSortSmallestDescription[] = _("POKéMON capturados del más\nbajo al más alto.");
const u8 gText_DexEmptyString[] = _("");
const u8 gText_DexSearchDontSpecify[] = _("NO ESPECIFICAR.");
const u8 gText_DexSearchTypeNone[] = _("NINGUNO");
const u8 gText_SelectorArrow[] = _("▶");
const u8 gText_EmptySpace[] = _(" "); // Unused
const u8 gText_WelcomeToHOF[] = _("¡Bienvenido al SALÓN DE LA FAMA!");
const u8 gText_HOFDexRating[] = _("POKéMON vistos: {STR_VAR_1}!\nPOKéMON capturados: {STR_VAR_2}!\p¡Valoración de la POKéDEX del PROF. ABEDUL!\pPROF. ABEDUL: Veamos…\p");
const u8 gText_HOFDexSaving[] = _("GUARDANDO…\nNO APAGUES LA CONSOLA.");
const u8 gText_HOFCorrupted[] = _("Los datos del SALÓN DE LA FAMA están dañados.");
const u8 gText_HOFNumber[] = _("SALÓN DE LA FAMA Nº {STR_VAR_1}");
const u8 gText_LeagueChamp[] = _("¡CAMPEÓN DE LA LIGA!\n¡ENHORABUENA!");
const u8 gText_Number[] = _("No. ");
const u8 gText_Level[] = _("Lv. ");
const u8 gText_IdNumberSlash[] = _("IDNo. /"); // Unused
const u8 gText_Name[] = _("NOMBRE");
const u8 gText_IDNumber[] = _("ID");
const u8 gText_BirchInTrouble[] = _("¡El PROF. ABEDUL está en apuros!\n¡Suelta un POKéMON y rescátalo!");
const u8 gText_ConfirmStarterChoice[] = _("¿Quieres este POKéMON?");
const u8 gText_Pokemon4[] = _("POKéMON"); // Unused
const u8 gText_FlyToWhere[] = _("¿A dónde VOLAR?");
const u8 gMenuText_Use[] = _("USAR");
const u8 gMenuText_Toss[] = _("TIRAR");
const u8 gMenuText_Register[] = _("REGISTRAR");
const u8 gMenuText_Give[] = _("DAR");
const u8 gMenuText_Confirm[] = _("CONFIRMAR");
const u8 gText_Cancel[] = _("CANCELAR");
const u8 gText_Cancel2[] = _("CANCELAR");
const u8 gText_EmptyString2[] = _("");
const u8 gText_None[] = _("NINGUNO");
const u8 gText_FiveMarks[] = _("?????");
const u8 gText_Slash[] = _("/");
const u8 gText_OneDash[] = _("-");
const u8 gText_TwoDashes[] = _("--");
const u8 gText_ThreeDashes[] = _("---");
const u8 gText_MaleSymbol[] = _("♂");
const u8 gText_FemaleSymbol[] = _("♀");
const u8 gText_LevelSymbol[] = _("{LV}");
const u8 gText_NumberClear01[] = _("{NO}{CLEAR 0x01}");
const u8 gText_RightArrow[] = _("{RIGHT_ARROW}"); // Unused
const u8 gText_IDNumber2[] = _("{ID}{NO}");
const u8 gText_Space[] = _(" ");
const u8 gText_SelectorArrow2[] = _("▶");
const u8 gText_GoBackPrevMenu[] = _("Volver al\nmenú anterior.");
const u8 gText_WhatWouldYouLike[] = _("¿Qué quieres hacer?");
const u8 gMenuText_Give2[] = _("DAR");
const u8 gText_xVar1[] = _("×{STR_VAR_1}");
const u8 gText_Berry2[] = _(" BAYA"); // Unused
const u8 gText_Coins[] = _("{STR_VAR_1} COINS");
const u8 gText_CloseBag[] = _("CERRAR MOCHILA");
const u8 gText_Var1IsSelected[] = _("{STR_VAR_1}\nseleccionado.");
const u8 gText_CantWriteMail[] = _("No puedes escribir\nCORREO aquí.");
const u8 gText_NoPokemon[] = _("No hay\nPOKéMON.");
const u8 gText_MoveVar1Where[] = _("¿Mover\n{STR_VAR_1}\na dónde?");
const u8 gText_Var1CantBeHeld[] = _("No se puede llevar\n{STR_VAR_1}.");
const u8 gText_TossHowManyVar1s[] = _("¿Cuántas\n{STR_VAR_1}\ntirar?");
const u8 gText_ThrewAwayVar2Var1s[] = _("Tiraste {STR_VAR_2}\n{STR_VAR_1}.");
const u8 gText_ConfirmTossItems[] = _("¿Tiras {STR_VAR_2}\n{STR_VAR_1}?");
const u8 gText_DadsAdvice[] = _("Consejo de PAPÁ…\n{PLAYER}, ¡hay un momento y un lugar\lpara cada cosa!{PAUSE_UNTIL_PRESS}");
const u8 gText_PlayerUsedVar2[] = _("{PLAYER} usó\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_RepelEffectsLingered[] = _("Pero el efecto de REPELENTE\nseguía activo.{PAUSE_UNTIL_PRESS}");
const u8 gText_LureEffectsLingered[] = _("Pero el efecto del CEBO\nseguía activo.{PAUSE_UNTIL_PRESS}");
const u8 gText_BoxFull[] = _("La CAJA está llena.{PAUSE_UNTIL_PRESS}");
const u8 gText_TheField[] = _("el campo");
const u8 gText_TheBattle[] = _("el combate");
const u8 gText_ThePokemonList[] = _("la lista de POKéMON");
const u8 gText_TheShop[] = _("la tienda");
const u8 gText_ThePC[] = _("el PC");
const u8 gText_ReelItIn[] = _("Mantén y suelta A para mantener al\nPOKéMON dentro de la barra.");
const u8 gText_HelpfulTextHigher0[] = _("¡Uf!\n¡Estuvo cerca!");
const u8 gText_HelpfulTextHigher1[] = _("¡Eso es!\n¡Sigue así!");
const u8 gText_HelpfulTextHigher2[] = _("¡Solo un poco más!");
const u8 gText_HelpfulTextLower0[] = _("¡Oh no!\n¡Está por escapar!");
const u8 gText_HelpfulTextLower1[] = _("¡Sí que pelea!");
const u8 gText_HelpfulTextLower2[] = _("¡Ay!\nCasi lo tenías.");
const u8 gText_FishingWantToQuit[] = _("¿Quieres dejar ir este?");
const u8 gText_ReeledInAPokemon[] = _("¡{PLAYER} enganchó un POKéMON!{PAUSE_UNTIL_PRESS}");
const u8 gText_PokemonGotAway[] = _("¡Oh no!\nEl POKéMON escapó…{PAUSE_UNTIL_PRESS}");
const u8 gText_ReeledInTreasure[] = _("¡{PLAYER} sacó un TESORO!");
const u8 gText_FoundATreasureItem[] = _("¡{PLAYER} encontró\n{STR_VAR_2}!");
const u8 gText_PutTreasureInPocket[] = _("{PLAYER} guardó {STR_VAR_2}\nen el BOLSILLO {STR_VAR_3}.");
const u8 gText_NoRoomForTreasure[] = _("¡Qué mala suerte!\nLa MOCHILA está llena…");

const u8 *const gBagMenu_ReturnToStrings[] =
{
    [ITEMMENULOCATION_FIELD]               = gText_TheField,
    [ITEMMENULOCATION_BATTLE]              = gText_TheBattle,
    [ITEMMENULOCATION_PARTY]               = gText_ThePokemonList,
    [ITEMMENULOCATION_SHOP]                = gText_TheShop,
    [ITEMMENULOCATION_BERRY_TREE]          = gText_TheField,
    [ITEMMENULOCATION_BERRY_BLENDER_CRUSH] = gText_TheField,
    [ITEMMENULOCATION_ITEMPC]              = gText_ThePC,
    [ITEMMENULOCATION_FAVOR_LADY]          = gText_TheField,
    [ITEMMENULOCATION_QUIZ_LADY]           = gText_TheField,
    [ITEMMENULOCATION_APPRENTICE]          = gText_TheField,
    [ITEMMENULOCATION_WALLY]               = gText_TheBattle,
    [ITEMMENULOCATION_PCBOX]               = gText_ThePC,
    [ITEMMENULOCATION_BERRY_TREE_MULCH]    = gText_TheField,
};

const u8 *const gPyramidBagMenu_ReturnToStrings[] =
{
    [PYRAMIDBAG_LOC_FIELD]       = gText_TheField,
    [PYRAMIDBAG_LOC_BATTLE]      = gText_TheBattle,
    [PYRAMIDBAG_LOC_PARTY]       = gText_ThePokemonList,
    [PYRAMIDBAG_LOC_CHOOSE_TOSS] = gText_TheField
};

const u8 gText_ReturnToVar1[] = _("Volver a\n{STR_VAR_1}.");

const u8 *const gPocketNamesStringsTable[] =
{
    [POCKET_ITEMS] =        COMPOUND_STRING("OBJETOS"),
    [POCKET_POKE_BALLS] =   COMPOUND_STRING("POKé BALLS"),
    [POCKET_TM_HM]  =       COMPOUND_STRING("MTs y MOs"),
    [POCKET_BERRIES] =      COMPOUND_STRING("BAYAS"),
    [POCKET_KEY_ITEMS] =    COMPOUND_STRING("OBJ. CLAVE")
};

const u8 gText_NumberItem_TMBerry[] = _("{NO}{STR_VAR_1}{CLEAR 0x03}{STR_VAR_2}");
const u8 gText_NumberItem_HM[] = _("{CLEAR_TO 0x11}{STR_VAR_1}{CLEAR 0x05}{STR_VAR_2}");

const u8 gText_ShopBuy[] = _("COMPRAR");
const u8 gText_ShopSell[] = _("VENDER");
const u8 gText_ShopQuit[] = _("SALIR");
const u8 gText_ThatItemIsSoldOut[] = _("Lo siento, ese objeto está agotado.{PAUSE_UNTIL_PRESS}");
const u8 gText_SoldOut[] = _("AGOTADO");
const u8 gText_InBagVar1[] = _("EN MOCHILA: {STR_VAR_1}");
const u8 gText_QuitShopping[] = _("Salir de la tienda.");
const u8 gText_Var1CertainlyHowMany[] = _("¿{STR_VAR_1}? Claro.\n¿Cuántos quieres?");
const u8 gText_Var1CertainlyHowMany2[] = _("¿{STR_VAR_1}? Claro.\n¿Cuántos quieres?");
const u8 gText_Var1AndYouWantedVar2[] = _("¿{STR_VAR_1}? ¿Y {STR_VAR_2}?\nEn total serán ¥{STR_VAR_3}.");
const u8 gText_Var1IsItThatllBeVar2[] = _("¿{STR_VAR_1}? Serán ¥{STR_VAR_2}.\n¿Lo quieres?");
const u8 gText_YouWantedVar1ThatllBeVar2[] = _("¿Quieres {STR_VAR_1}?\nSerán ¥{STR_VAR_2}. ¿Te parece bien?");
const u8 gText_HereYouGoThankYou[] = _("¡Aquí tienes!\nMuchas gracias.");
const u8 gText_ThankYouIllSendItHome[] = _("¡Gracias!\nLo enviaré a tu PC.");
const u8 gText_ThanksIllSendItHome[] = _("¡Gracias!\nLo enviaré a tu PC.");
const u8 gText_YouDontHaveMoney[] = _("No tienes suficiente dinero.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMoreRoomForThis[] = _("No tienes sitio para este\nobjeto.{PAUSE_UNTIL_PRESS}");
const u8 gText_SpaceForVar1Full[] = _("No queda espacio para {STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_AnythingElseICanHelp[] = _("¿Puedo ayudarte en algo más?");
const u8 gText_CanIHelpWithAnythingElse[] = _("¿Puedo ayudarte en algo más?");
const u8 gText_ThrowInPremierBall[] = _("También te doy una PREMIER BALL.{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowInPremierBalls[] = _("También te doy {STR_VAR_1} PREMIER BALLS.{PAUSE_UNTIL_PRESS}");
const u8 gText_CantBuyKeyItem[] = _("{STR_VAR_2}? Oh, no.\nNo puedo comprarlo.{PAUSE_UNTIL_PRESS}");
const u8 gText_HowManyToSell[] = _("{STR_VAR_2}?\n¿Cuántos quieres vender?");
const u8 gText_ICanPayVar1[] = _("Puedo pagar ¥{STR_VAR_1}.\n¿Te parece bien?");
const u8 gText_TurnedOverVar1ForVar2[] = _("Entregaste {STR_VAR_2}\ny recibiste ¥{STR_VAR_1}.");
const u8 gText_PokedollarVar1[] = _("¥{STR_VAR_1}");
const u8 gText_HP3[] = _("HP");
const u8 gText_SpAtk3[] = _("SP. ATK");
const u8 gText_SpDef3[] = _("SP. DEF");
const u8 gText_WontHaveEffect[] = _("No tendrá ningún efecto.{PAUSE_UNTIL_PRESS}");
const u8 gText_NextFusionMon[] = _("Elige {PKMN} para fusionar.");
const u8 gText_CantBeUsedOnPkmn[] = _("No se puede usar\nen ese POKéMON.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCantSwitchOut[] = _("{STR_VAR_1} no puede\nretirarse.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyInBattle[] = _("{STR_VAR_1} ya está\nen combate.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadySelected[] = _("{STR_VAR_1} ya ha sido\nseleccionado.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHasNoEnergy[] = _("{STR_VAR_1} no tiene energía\npara luchar.{PAUSE_UNTIL_PRESS}");
const u8 gText_CantSwitchWithAlly[] = _("No puedes cambiar el POKéMON\nde {STR_VAR_1} por el tuyo.{PAUSE_UNTIL_PRESS}");
const u8 gText_EggCantBattle[] = _("¡Un HUEVO no puede combatir!{PAUSE_UNTIL_PRESS}");
const u8 gText_CantUseUntilNewBadge[] = _("No se puede usar hasta conseguir\nuna nueva MEDALLA.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMoreThanVar1Pkmn[] = _("No pueden participar más\nde {STR_VAR_1} POKéMON.{PAUSE_UNTIL_PRESS}");
const u8 gText_SendMailToPC[] = _("¿Enviar la CARTA a tu PC?");
const u8 gText_MailSentToPC[] = _("La CARTA se envió a tu PC.{PAUSE_UNTIL_PRESS}");
const u8 gText_PCMailboxFull[] = _("El buzón de tu PC está lleno.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailMessageWillBeLost[] = _("Si quitas la CARTA,\nse perderá el mensaje. ¿Vale?");
const u8 gText_RemoveMailBeforeItem[] = _("Debes quitar la CARTA antes\nde darle un objeto.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWasGivenItem[] = _("{STR_VAR_1} recibió\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyHoldingItemSwitch[] = _("{STR_VAR_1} ya lleva\n{STR_VAR_2}.\p¿Quieres cambiar los dos\nobjetos?");
const u8 gText_PkmnNotHolding[] = _("{STR_VAR_1} no lleva\nnada.{PAUSE_UNTIL_PRESS}");
const u8 gText_ReceivedItemFromPkmn[] = _("Received the {STR_VAR_2}\nfrom {STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTakenFromPkmn[] = _("Se retiró el CORREO\ndel POKéMON.{PAUSE_UNTIL_PRESS}");
const u8 gText_SwitchedPkmnItem[] = _("The {STR_VAR_2} was taken and\nreplaced with the {STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHoldingItemCantHoldMail[] = _("Este POKéMON lleva un\nobjeto. No puede llevar CORREO.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTransferredFromMailbox[] = _("MAIL was transferred from\nthe MAILBOX.{PAUSE_UNTIL_PRESS}");
const u8 gText_BagFullCouldNotRemoveItem[] = _("La MOCHILA está llena. No se\npudo retirar el objeto del POKéMON.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnLearnedMove3[] = _("{STR_VAR_1} learned\n{STR_VAR_2}!");
const u8 gText_PkmnCantLearnMove[] = _("{STR_VAR_1} y {STR_VAR_2}\nno son compatibles.\pNo se puede aprender\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnNeedsToReplaceMove[] = _("{STR_VAR_1} wants to learn the\nmove {STR_VAR_2}.\pHowever, {STR_VAR_1} already\nknows four moves.\pShould a move be deleted and\nreplaced with {STR_VAR_2}?");
const u8 gText_StopLearningMove2[] = _("Stop trying to teach\n{STR_VAR_2}?");
const u8 gText_MoveNotLearned[] = _("{STR_VAR_1} did not learn the\nmove {STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_WhichMoveToForget[] = _("Which move should be forgotten?{PAUSE_UNTIL_PRESS}");
const u8 gText_12PoofForgotMove[] = _("1, {PAUSE 15}2, and{PAUSE 15}… {PAUSE 15}… {PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}Poof!\p{STR_VAR_1} forgot how to\nuse {STR_VAR_2}.\pAnd…{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyKnows[] = _("{STR_VAR_1} already knows\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHPRestoredByVar2[] = _("{STR_VAR_1}'s HP was restored\nby {STR_VAR_2} point(s).{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfPoison[] = _("{STR_VAR_1} was cured of its\npoisoning.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfParalysis[] = _("{STR_VAR_1} was cured of\nparalysis.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWokeUp2[] = _("{STR_VAR_1} woke up.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnBurnHealed[] = _("{STR_VAR_1}'s burn was healed.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFrostbiteHealed[] = _("{STR_VAR_1}'s frostbite was healed.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnThawedOut[] = _("{STR_VAR_1} was thawed out.{PAUSE_UNTIL_PRESS}");
const u8 gText_PPWasRestored[] = _("PP was restored.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnRegainhedHealth[] = _("{STR_VAR_1} regained health.{PAUSE_UNTIL_PRESS}"); // Unused
const u8 gText_PkmnBecameHealthy[] = _("{STR_VAR_1} became healthy.{PAUSE_UNTIL_PRESS}");
const u8 gText_MovesPPIncreased[] = _("{STR_VAR_1}'s PP increased.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnElevatedToLvVar2[] = _("{STR_VAR_1} was elevated to\nLv. {STR_VAR_2}.");
const u8 gText_PkmnGainedExp[] = _("{STR_VAR_1} gained {STR_VAR_2} Exp. Points!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGainedExpAndElevatedToLvVar3[] = _("{STR_VAR_1} gained {STR_VAR_2} Exp. Points\nand was elevated to Lv. {STR_VAR_3}!");
const u8 gText_PkmnBaseVar2StatIncreased[] = _("{STR_VAR_1}'s base {STR_VAR_2}\nstat was raised.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFriendlyBaseVar2Fell[] = _("{STR_VAR_1} turned friendly.\nThe base {STR_VAR_2} fell!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAdoresBaseVar2Fell[] = _("{STR_VAR_1} adores you!\nThe base {STR_VAR_2} fell!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFriendlyBaseVar2CantFall[] = _("{STR_VAR_1} se ha hecho amigo.\n¡La base {STR_VAR_2} no puede bajar!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnSnappedOutOfConfusion[] = _("{STR_VAR_1} snapped out of its\nconfusion.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGotOverInfatuation[] = _("{STR_VAR_1} got over its\ninfatuation.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnTransformed[] = _("{STR_VAR_1} transformed!{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowAwayItem[] = _("¿Tirar este\n{STR_VAR_1}?");
const u8 gText_ItemThrownAway[] = _("Se tiró {STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_TeachWhichPokemon2[] = _("¿A qué POKéMON enseñarle?"); // Unused
const u8 gText_ChoosePokemon[] = _("Elige un POKéMON.");
const u8 gText_MoveToWhere[] = _("¿Mover a dónde?");
const u8 gText_TeachWhichPokemon[] = _("¿A qué POKéMON enseñarle?");
const u8 gText_UseOnWhichPokemon[] = _("¿En qué POKéMON usarlo?");
const u8 gText_GiveToWhichPokemon[] = _("¿A qué POKéMON dárselo?");
const u8 gText_DoWhatWithPokemon[] = _("¿Qué hacer con {PKMN}?");
const u8 gText_NothingToCut[] = _("No hay nada que CORTAR.");
const u8 gText_CantSurfHere[] = _("No puedes usar SURF aquí.");
const u8 gText_AlreadySurfing[] = _("Ya estás usando SURF.");
const u8 gText_CantUseHere[] = _("No se puede usar aquí.");
const u8 gText_RestoreWhichMove[] = _("¿Restaurar qué movimiento?");
const u8 gText_BoostPp[] = _("¿Mejorar PP de qué movimiento?");
const u8 gText_DoWhatWithItem[] = _("¿Qué hacer con el objeto?");
const u8 gText_NoPokemonForBattle[] = _("No hay POKéMON\npara luchar.");
const u8 gText_ChoosePokemon2[] = _("Elige un POKéMON.");
const u8 gText_NotEnoughHp[] = _("No hay PS suficientes…");
const u8 gText_PokemonAreNeeded[] = _("Se necesitan {STR_VAR_1}\nPOKéMON.");
const u8 gText_PokemonCantBeSame[] = _("Los POKéMON no\npueden ser iguales.");
const u8 gText_NoIdenticalHoldItems[] = _("No puede haber objetos\niguales.");
const u8 gText_CurrentIsTooFast[] = _("¡La corriente es demasiado fuerte!");
const u8 gText_DoWhatWithMail[] = _("¿Qué hacer con el CORREO?");
const u8 gText_ChoosePokemonCancel[] = _("Elige POKéMON o CANCELAR.");
const u8 gText_ChoosePokemonConfirm[] = _("Elige POKéMON y confirma.");
const u8 gText_SendWhichMonToPC[] = _("¿Enviar qué POKéMON al PC?");
const u8 gText_MoveItemWhere[] = _("¿Mover el objeto a dónde?");
const u8 gText_XsYAnd[] = _("{STR_VAR_1}'s {STR_VAR_2} and\n");
const u8 gText_XsYWereSwapped[] = _("{STR_VAR_1}'s {STR_VAR_2} were swapped!{PAUSE_UNTIL_PRESS}");
const u8 gText_EnjoyCycling[] = _("¡A disfrutar de la bici!");
const u8 gText_InUseAlready_PM[] = _("Esto ya está en uso.");
const u8 gText_AlreadyHoldingOne[] = _("{STR_VAR_1} ya lleva\nun {STR_VAR_2}.");
const u8 gText_WhichAppliance[] = _("¿Qué\naparato elegir?");
const u8 gText_NoUse[] = _("No se puede usar.");
const u8 gText_Able[] = _("APTO");
const u8 gText_First_PM[] = _("PRIMERO");
const u8 gText_Second_PM[] = _("SEGUNDO");
const u8 gText_Third_PM[] = _("TERCERO");
const u8 gText_Able2[] = _("APTO");
const u8 gText_NotAble[] = _("NO APTO");
const u8 gText_Able3[] = _("¡APTO!");
const u8 gText_NotAble2[] = _("¡NO APTO!");
const u8 gText_Learned[] = _("APRENDIÓ");
const u8 gText_Have[] = _("TIENE");
const u8 gText_DontHave[] = _("NO TIENE");
const u8 gText_Fourth[] = _("CUARTO");
const u8 gText_PkmnCantParticipate[] = _("Ese POKéMON no puede\nparticipar.{PAUSE_UNTIL_PRESS}");
const u8 gText_CancelParticipation[] = _("¿Cancelar la participación?");
const u8 gText_CancelBattle[] = _("¿Cancelar el combate?");
const u8 gText_ReturnToWaitingRoom[] = _("¿Volver a la SALA DE ESPERA?");
const u8 gText_CancelChallenge[] = _("¿Cancelar el desafío?");
const u8 gText_EscapeFromHere[] = _("¿Quieres salir de aquí y volver\na {STR_VAR_1}?");
const u8 gText_ReturnToHealingSpot[] = _("¿Volver al último lugar de curación\nusado en {STR_VAR_1}?");
const u8 gText_PauseUntilPress[] = _("{PAUSE_UNTIL_PRESS}");
const u8 gJPText_AreYouSureYouWantToSpinTradeMon[] = _("{STR_VAR_1}を ぐるぐるこうかんに\nだして よろしいですか？");
ALIGNED(4) const u8 gText_OnlyPkmnForBattle[] = _("Es tu único\nPOKéMON para luchar.");
ALIGNED(4) const u8 gText_PkmnCantBeTradedNow[] = _("Ese POKéMON no puede\nintercambiarse ahora.");
ALIGNED(4) const u8 gText_PkmnCantBeTraded[] = _("Ese POKéMON no puede\nintercambiarse.");
ALIGNED(4) const u8 gText_EggCantBeTradedNow[] = _("Un HUEVO no puede\nintercambiarse ahora.");
ALIGNED(4) const u8 gText_OtherTrainersPkmnCantBeTraded[] = _("El POKéMON del otro ENTRENADOR\nno puede intercambiarse ahora.");
ALIGNED(4) const u8 gText_OtherTrainerCantAcceptPkmn[] = _("El otro ENTRENADOR no puede\naceptar ese POKéMON ahora.");
ALIGNED(4) const u8 gText_CantTradeWithTrainer[] = _("No puedes intercambiar con ese\nENTRENADOR ahora.");
ALIGNED(4) const u8 gText_NotPkmnOtherTrainerWants[] = _("Ese no es el tipo de POKéMON\nque quiere el otro ENTRENADOR.");
ALIGNED(4) const u8 gText_ThatIsntAnEgg[] = _("Eso no es un HUEVO.");
const u8 gText_Register[] = _("REGISTRAR");
const u8 gText_Attack3[] = _("ATAQUE");
const u8 gText_Defense3[] = _("DEFENSA");
const u8 gText_SpAtk4[] = _("AT. ESP.");
const u8 gText_SpDef4[] = _("DEF. ESP.");
const u8 gText_Speed2[] = _("VELOC.");
const u8 gText_HP4[] = _("HP");
const u8 gText_EmptyString8[] = _(""); // Unused
const u8 gText_OTSlash[] = _("OT/");
const u8 gText_RentalPkmn[] = _("POKéMON DE PRÉSTAMO");
const u8 gText_TypeSlash[] = _("TYPE/");
const u8 gText_Power[] = _("POWER");
const u8 gText_Accuracy2[] = _("ACCURACY");
const u8 gText_Appeal[] = _("APPEAL");
const u8 gText_Jam[] = _("JAM");
const u8 gText_Status[] = _("STATUS");
const u8 gText_ExpPoints[] = _("EXP. POINTS");
const u8 gText_NextLv[] = _("NEXT LV.");
const u8 gText_RibbonsVar1[] = _("RIBBONS: {STR_VAR_1}");
const u8 gText_EmptyString5[] = _("");
const u8 gText_Events[] = _("EVENTS"); // Unused
const u8 gText_Switch[] = _("SWITCH");
const u8 gText_PkmnInfo[] = _("INFO. POKéMON");
const u8 gText_PkmnSkills[] = _("HABIL. POKéMON");
const u8 gText_BattleMoves[] = _("MOVIMIENTOS COMBATE");
const u8 gText_ContestMoves[] = _("MOVS. CONCURSO");
const u8 gText_Info[] = _("INFO");
const u8 gText_EggWillTakeALongTime[] = _("Parece que este HUEVO tardará\nmucho en eclosionar.");
const u8 gText_EggWillTakeSomeTime[] = _("¿Qué saldrá de aquí?\nTardará un tiempo.");
const u8 gText_EggWillHatchSoon[] = _("It moves occasionally.\nIt should hatch soon.");
const u8 gText_EggAboutToHatch[] = _("It's making sounds.\nIt's about to hatch!");
const u8 gText_HMMovesCantBeForgotten2[] = _("Las MO no pueden olvidarse\nahora.");
const u8 gText_XNatureMetAtYZ[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}.\nEncontrado en {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u8 gText_XNatureHatchedAtYZ[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}.\nEclosionó en {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u8 gText_XNatureObtainedInTrade[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}.\nObtenido en un intercambio.");
const u8 gText_XNatureFatefulEncounter[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}.\nObtenido en un encuentro\ndestino en {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u8 gText_XNatureProbablyMetAt[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}.\nProbablemente encontrado en {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u8 gText_XNature[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}");
const u8 gText_XNatureMetSomewhereAt[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}.\nEncontrado en algún lugar en {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u8 gText_XNatureHatchedSomewhereAt[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}.\nEclosionó en algún lugar en {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u8 gText_OddEggFoundByCouple[] = _("Un HUEVO POKéMON extraño hallado\npor la pareja de la GUARDERÍA.");
const u8 gText_PeculiarEggNicePlace[] = _("Un HUEVO POKéMON peculiar\nobtenido en un lugar agradable.");
const u8 gText_PeculiarEggTrade[] = _("Un HUEVO POKéMON peculiar\nobtenido en un intercambio.");
const u8 gText_EggFromHotSprings[] = _("Un HUEVO POKéMON obtenido\nen las aguas termales.");
const u8 gText_EggFromTraveler[] = _("Un HUEVO POKéMON extraño\nobtenido de un viajero.");
const u8 gText_ApostropheSBase[] = _("'s BASE");
const u8 gText_OkayToDeleteFromRegistry[] = _("Is it okay to delete {STR_VAR_1}\nfrom the REGISTRY?");
const u8 gText_RegisteredDataDeleted[] = _("The registered data was deleted.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoRegistry[] = _("No hay REGISTRO.{PAUSE_UNTIL_PRESS}");
const u8 gText_DelRegist[] = _("DEL REGIST.");
const u8 gText_Var3Var1SlashVar2[] = _("{STR_VAR_3}{STR_VAR_1}/{STR_VAR_2}"); // Unused
const u8 gText_Decorate[] = _("DECORATE");
const u8 gText_PutAway[] = _("PUT AWAY");
const u8 gText_Toss2[] = _("TOSS");
const u8 gText_Color161Shadow161[] = _("{COLOR 161}{SHADOW 161}");
const u8 gText_PutOutSelectedDecorItem[] = _("Coloca la decoración seleccionada.");
const u8 gText_StoreChosenDecorInPC[] = _("Guarda la decoración en el PC.");
const u8 gText_ThrowAwayUnwantedDecors[] = _("Tira las decoraciones no deseadas.");
const u8 gText_NoDecorations[] = _("No hay decoraciones.{PAUSE_UNTIL_PRESS}");
const u8 gText_Desk[] = _("DESK");
const u8 gText_Chair[] = _("CHAIR");
const u8 gText_Plant[] = _("PLANT");
const u8 gText_Ornament[] = _("ORNAMENT");
const u8 gText_Mat[] = _("MAT");
const u8 gText_Poster[] = _("POSTER");
const u8 gText_Doll[] = _("DOLL");
const u8 gText_Cushion[] = _("CUSHION");
const u8 gText_Gold[] = _("ORO");
const u8 gText_Silver[] = _("PLATA");
const u8 gText_PlaceItHere[] = _("¿Colocarlo aquí?");
const u8 gText_CantBePlacedHere[] = _("No se puede colocar aquí.");
const u8 gText_CancelDecorating[] = _("¿Cancelar decoración?");
const u8 gText_InUseAlready[] = _("Esto ya está en uso.");
const u8 gText_NoMoreDecorations[] = _("No se pueden colocar más\ndecoraciones. El máximo es {STR_VAR_1}.");
const u8 gText_NoMoreDecorations2[] = _("No se pueden colocar más\ndecoraciones. El máximo es {STR_VAR_1}.");
const u8 gText_MustBePlacedOnDesk[] = _("No se puede colocar aquí.\nDebe ir en una MESA, etc."); // Unused
const u8 gText_CantPlaceInRoom[] = _("No se puede poner esta decoración\nen tu propia habitación.");
const u8 gText_CantThrowAwayInUse[] = _("Esta decoración está en uso.\nNo se puede tirar.");
const u8 gText_DecorationWillBeDiscarded[] = _("Se tirará {STR_VAR_1}.\n¿Te parece bien?");
const u8 gText_DecorationThrownAway[] = _("Se tiró la decoración.");
const u8 gText_StopPuttingAwayDecorations[] = _("¿Dejar de guardar decoraciones?");
const u8 gText_NoDecorationHere[] = _("No hay ninguna decoración aquí.");
const u8 gText_ReturnDecorationToPC[] = _("¿Devolver esta decoración al PC?");
const u8 gText_DecorationReturnedToPC[] = _("La decoración volvió al PC.");
const u8 gText_NoDecorationsInUse[] = _("No hay decoraciones en uso.{PAUSE_UNTIL_PRESS}");
const u8 gText_Tristan[] = _("TRISTAN");
const u8 gText_Philip[] = _("PHILIP");
const u8 gText_Dennis[] = _("DENNIS");
const u8 gText_Roberto[] = _("ROBERTO");
const u8 gText_NoItems[] = _("No hay objetos.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMailHere[] = _("There's no MAIL here.{PAUSE_UNTIL_PRESS}");
const u8 gText_WhatToDoWithVar1sMail[] = _("¿Qué quieres hacer con\nel CORREO de {STR_VAR_1}?");
const u8 gText_MessageWillBeLost[] = _("The message will be lost.\nIs that okay?");
const u8 gText_BagIsFull[] = _("La MOCHILA está llena.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailToBagMessageErased[] = _("El CORREO volvió a la MOCHILA\ncon su mensaje borrado.{PAUSE_UNTIL_PRESS}");
const u8 gText_Dad[] = _("DAD");
const u8 gText_Mom[] = _("MOM");
const u8 gText_Wallace[] = _("WALLACE");
const u8 gText_Steven[] = _("STEVEN");
const u8 gText_Brawly[] = _("BRAWLY");
const u8 gText_Winona[] = _("WINONA");
const u8 gText_Phoebe[] = _("PHOEBE");
const u8 gText_Glacia[] = _("GLACIA");
const u8 gText_Info2[] = _("INFO");
const u8 gText_CoolnessContest[] = _("CONCURSO CARISMA");
const u8 gText_BeautyContest[] = _("CONCURSO BELLEZA");
const u8 gText_CutenessContest[] = _("CONCURSO DULZURA");
const u8 gText_SmartnessContest[] = _("CONCURSO INGENIO");
const u8 gText_ToughnessContest[] = _("CONCURSO DUREZA");
const u8 gText_Decoration2[] = _("DECORATION");
const u8 gText_PackUp[] = _("PACK UP");
const u8 gText_Registry[] = _("REGISTRY");
const u8 gText_Information[] = _("INFORMATION");
const u8 gText_Yes[] = _("SÍ");
const u8 gText_No[] = _("NO");
const u8 gText_Lv50[] = _("LV. 50");
const u8 gText_OpenLevel[] = _("OPEN LEVEL");
const u8 gText_RedShard[] = _("RED SHARD");
const u8 gText_YellowShard[] = _("YELLOW SHARD");
const u8 gText_BlueShard[] = _("BLUE SHARD");
const u8 gText_GreenShard[] = _("GREEN SHARD");
const u8 gText_BattleFrontier[] = _("FRENTE BATALLA");
const u8 gText_Cool[] = _("COOL");
const u8 gText_Beauty[] = _("BEAUTY");
const u8 gText_Cute[] = _("CUTE");
const u8 gText_Smart[] = _("SMART");
const u8 gText_Tough[] = _("TOUGH");
const u8 gText_Normal[] = _("NORMAL");
const u8 gText_Super[] = _("SUPER");
const u8 gText_Hyper[] = _("HYPER");
const u8 gText_Master[] = _("MASTER");
const u8 gText_Cool2[] = _("COOL");
const u8 gText_Beauty2[] = _("BEAUTY");
const u8 gText_Cute2[] = _("CUTE");
const u8 gText_Smart2[] = _("SMART");
const u8 gText_Tough2[] = _("TOUGH");
const u8 gText_Items[] = _("ITEMS");
const u8 gText_Key_Items[] = _("KEY ITEMS");
const u8 gText_Poke_Balls[] = _("POKé BALLS");
const u8 gText_TMs_Hms[] = _("TMs & HMs");
const u8 gText_Berries2[] = _("BERRIES");
const u8 gText_SomeonesPC[] = _("SOMEONE'S PC");
const u8 gText_LanettesPC[] = _("LANETTE'S PC");
const u8 gText_PlayersPC[] = _("{PLAYER}'s PC");
const u8 gText_HallOfFame[] = _("HALL OF FAME");
const u8 gText_LogOff[] = _("LOG OFF");
const u8 gText_Opponent[] = _("OPPONENT");
const u8 gText_Tourney_Tree[] = _("TOURNEY TREE");
const u8 gText_ReadyToStart[] = _("READY TO START");
const u8 gText_Single2[] = _("INDIVIDUAL");
const u8 gText_Double2[] = _("DOBLE");
const u8 gText_Multi[] = _("MULTI");
const u8 gText_MultiLink[] = _("MULTI-ENLACE");
const u8 gText_MenuOptionPokedex[] = _("POKéDEX");
const u8 gText_MenuOptionPokemon[] = _("POKéMON");
const u8 gText_MenuOptionBag[] = _("MOCHILA");
const u8 gText_MenuOptionPokenav[] = _("POKéNAV");
const u8 gText_Blank[] = _("");
const u8 gText_MenuOptionSave[] = _("GUARDAR");
const u8 gText_MenuOptionOption[] = _("OPCIONES");
const u8 gText_MenuOptionExit[] = _("SALIR");
const u8 gText_SouthernIsland[] = _("ISLA DEL SUR");
const u8 gText_BirthIsland[] = _("ISLA ORIGEN");
const u8 gText_FarawayIsland[] = _("ISLA LEJANA");
const u8 gText_NavelRock[] = _("ROCA OMBLIGO");
const u8 gText_NormalTagMatch[] = _("COMBATE NORMAL");
const u8 gText_VarietyTagMatch[] = _("COMBATE VARIADO");
const u8 gText_UniqueTagMatch[] = _("COMBATE ÚNICO");
const u8 gText_ExpertTagMatch[] = _("COMBATE EXPERTO");
const u8 gText_TradeCenter[] = _("CENTRO DE INTERCAMBIO");
const u8 gText_Colosseum[] = _("COLISEO");
const u8 gText_RecordCorner[] = _("ESQUINA RÉCORD");
const u8 gText_BerryCrush3[] = _("MACHACA BAYAS");
const u8 gText_BattleRules[] = _("REGLAS DE COMBATE");
const u8 gText_JudgeMind[] = _("JUEZ: MENTE");
const u8 gText_JudgeSkill[] = _("JUEZ: HABILIDAD");
const u8 gText_JudgeBody[] = _("JUEZ: CUERPO");
const u8 gText_BasicRules[] = _("REGLAS BÁSICAS");
const u8 gText_SwapPartners[] = _("CAMBIO: COMPAÑ.");
const u8 gText_SwapNumber[] = _("CAMBIO: NÚMERO");
const u8 gText_SwapNotes[] = _("CAMBIO: NOTAS");
const u8 gText_BattleBasics[] = _("BÁSICOS DEL COMBATE");
const u8 gText_PokemonNature[] = _("NATURALEZA POKéMON");
const u8 gText_PokemonMoves[] = _("MOVS. POKéMON");
const u8 gText_Underpowered[] = _("POCA FUERZA");
const u8 gText_WhenInDanger[] = _("EN PELIGRO");
const u8 gText_BattlePokemon[] = _("COMBATIR POKéMON");
const u8 gText_BattleTrainers[] = _("COMBATIR ENTRENADORES");
const u8 gText_GoOn[] = _("SEGUIR");
const u8 gText_Record2[] = _("RÉCORD");
const u8 gText_Rest[] = _("DESCANSAR");
const u8 gText_Retire[] = _("RETIRARSE");
const u8 gText_1F[] = _("1F");
const u8 gText_2F[] = _("2F");
const u8 gText_3F[] = _("3F");
const u8 gText_4F[] = _("4F");
const u8 gText_5F[] = _("5F");
const u8 gText_6F[] = _("6F");
const u8 gText_7F[] = _("7F");
const u8 gText_8F[] = _("8F");
const u8 gText_9F[] = _("9F");
const u8 gText_10F[] = _("10F");
const u8 gText_11F[] = _("11F");
const u8 gText_B1F[] = _("B1F");
const u8 gText_B2F[] = _("B2F");
const u8 gText_B3F[] = _("B3F");
const u8 gText_B4F[] = _("B4F");
const u8 gText_Rooftop[] = _("ROOFTOP");
const u8 gText_ElevatorNowOn[] = _("Now on:");
const u8 gText_BP[] = _("BP");
const u8 gText_RankingHall[] = _("RANKING HALL");
const u8 gText_ExchangeService[] = _("EXCHANGE SERVICE");
const u8 gText_LilycoveCity[] = _("LILYCOVE CITY");
const u8 gText_SlateportCity[] = _("SLATEPORT CITY");
const u8 gText_Exit[] = _("SALIR");
const u8 gText_YourPartysFull[] = _("Your party's full!{PAUSE_UNTIL_PRESS}");
const u8 gText_NatureSlash[] = _("NATURE/");
const u8 gText_InParty[] = _("IN PARTY");
const u8 gText_PokemonMaleLv[] = _("{DYNAMIC 0}{COLOR_HIGHLIGHT_SHADOW LIGHT_RED WHITE GREEN}♂{COLOR_HIGHLIGHT_SHADOW DARK_GRAY WHITE LIGHT_GRAY}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonFemaleLv[] = _("{DYNAMIC 0}{COLOR_HIGHLIGHT_SHADOW LIGHT_GREEN WHITE BLUE}♀{COLOR_HIGHLIGHT_SHADOW DARK_GRAY WHITE LIGHT_GRAY}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonNoGenderLv[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonMaleLv2[] = _("{DYNAMIC 0}{COLOR_HIGHLIGHT_SHADOW LIGHT_RED WHITE GREEN}♂{COLOR_HIGHLIGHT_SHADOW DARK_GRAY WHITE LIGHT_GRAY}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonFemaleLv2[] = _("{DYNAMIC 0}{COLOR_HIGHLIGHT_SHADOW LIGHT_GREEN WHITE BLUE}♀{COLOR_HIGHLIGHT_SHADOW DARK_GRAY WHITE LIGHT_GRAY}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonNoGenderLv2[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_CombineFourWordsOrPhrases[] = _("Combine four words or phrases");
const u8 gText_AndMakeYourProfile[] = _("and make your profile.");
const u8 gText_CombineSixWordsOrPhrases[] = _("Combine six words or phrases");
const u8 gText_AndMakeAMessage[] = _("and make a message.");
const u8 gText_FindWordsThatDescribeYour[] = _("Find words that describe your");
const u8 gText_FeelingsRightNow[] = _("feelings right now.");
const u8 gText_WithFourPhrases[] = _("With four phrases,"); // Unused
const u8 gText_CombineNineWordsOrPhrases[] = _("Combine nine words or phrases");
const u8 gText_AndMakeAMessage2[] = _("and make a message.");
const u8 gText_ChangeJustOneWordOrPhrase[] = _("Change just one word or phrase");
const u8 gText_AndImproveTheBardsSong[] = _("and improve the BARD's song.");
const u8 gText_YourProfile[] = _("Your profile");
const u8 gText_YourFeelingAtTheBattlesStart[] = _("Your feeling at the battle's start");
const u8 gText_WhatYouSayIfYouWin[] = _("What you say if you win a battle");
const u8 gText_WhatYouSayIfYouLose[] = _("What you say if you lose a battle");
const u8 gText_TheAnswer[] = _("The answer");
const u8 gText_TheMailMessage[] = _("The MAIL message");
const u8 gText_TheMailSalutation[] = _("The MAIL salutation"); // Unused
const u8 gText_TheBardsSong2[] = _("The new song");
const u8 gText_CombineTwoWordsOrPhrases[] = _("Combine two words or phrases");
const u8 gText_AndMakeATrendySaying[] = _("and make a trendy saying.");
const u8 gText_TheTrendySaying[] = _("The trendy saying");
const u8 gText_IsAsShownOkay[] = _("is as shown. Okay?");
const u8 gText_CombineTwoWordsOrPhrases2[] = _("Combine two words or phrases");
const u8 gText_ToTeachHerAGoodSaying[] = _("to teach her a good saying.");
const u8 gText_FindWordsWhichFit[] = _("Find words which fit");
const u8 gText_TheTrainersImage[] = _("the TRAINER's image.");
const u8 gText_TheImage[] = _("The image:");
const u8 gText_OutOfTheListedChoices[] = _("Out of the listed choices,");
const u8 gText_SelectTheAnswerToTheQuiz[] = _("¡Elige la respuesta del cuestionario!");
const u8 gText_AndCreateAQuiz[] = _("and create a quiz!");
const u8 gText_PickAWordOrPhraseAnd[] = _("Pick a word or phrase and");
const u8 gText_SetTheQuizAnswer[] = _("set the quiz answer.");
const u8 gText_TheAnswerColon[] = _("The answer:");
const u8 gText_TheQuizColon[] = _("The quiz:"); // Unused
const u8 gText_ApprenticePhrase[] = _("Frase del aprendiz:");
const u8 gText_QuitEditing[] = _("¿Salir de la edición?");
const u8 gText_StopGivingPkmnMail[] = _("¿Dejar de dar CORREO al POKéMON?");
const u8 gText_AndFillOutTheQuestionnaire[] = _("y completa el cuestionario.");
const u8 gText_LetsReplyToTheInterview[] = _("¡Vamos a responder la entrevista!");
const u8 gText_AllTextBeingEditedWill[] = _("Todo el texto editado");
const u8 gText_BeDeletedThatOkay[] = _("se borrará. ¿Está bien?");
const u8 gText_QuitEditing2[] = _("¿Salir de la edición?"); // Unused
const u8 gText_EditedTextWillNotBeSaved[] = _("El texto editado no se guardará."); // Unused
const u8 gText_IsThatOkay[] = _("¿Está bien?"); // Unused
const u8 gText_PleaseEnterPhraseOrWord[] = _("Introduce una palabra o frase."); // Unused
const u8 gText_EntireTextCantBeDeleted[] = _("No se puede borrar todo el texto.");
const u8 gText_OnlyOnePhrase[] = _("Solo se puede cambiar una frase.");
const u8 gText_OriginalSongWillBeUsed[] = _("Se usará la canción original.");
const u8 gText_ThatsTrendyAlready[] = _("¡Eso ya está de moda!"); // Unused
const u8 gText_CombineTwoWordsOrPhrases3[] = _("Combina dos palabras o frases.");
const u8 gText_QuitGivingInfo[] = _("¿Dejar de dar información?"); // Unused
const u8 gText_StopGivingPkmnMail2[] = _("¿Dejar de dar CORREO al POKéMON?"); // Unused
const u8 gText_CreateAQuiz2[] = _("¡Crea un cuestionario!"); // Unused
const u8 gText_SetTheAnswer[] = _("¡Elige la respuesta!"); // Unused
const u8 gText_CancelSelection[] = _("¿Cancelar la selección?"); // Unused
const u8 gText_Profile[] = _("PERFIL");
const u8 gText_AtTheBattlesStart[] = _("Al empezar el combate:");
const u8 gText_UponWinningABattle[] = _("Al ganar un combate:");
const u8 gText_UponLosingABattle[] = _("Al perder un combate:");
const u8 gText_TheBardsSong[] = _("La canción del BARDO");
const u8 gText_WhatsHipAndHappening[] = _("¿Qué se lleva ahora?");
const u8 gText_Interview[] = _("Entrevista");
const u8 gText_GoodSaying[] = _("Buena frase");
const u8 gText_FansQuestion[] = _("Pregunta de un fan");
const u8 gJPText_WhatIsTheQuizAnswer[] = _("クイズの こたえは？"); // Unused
const u8 gText_ApprenticesPhrase[] = _("Frase del aprendiz");
const u8 gText_Questionnaire[] = _("CUESTIONARIO");
const u8 gText_YouCannotQuitHere[] = _("No puedes salir aquí.");
const u8 gText_SectionMustBeCompleted[] = _("Debes completar esta sección.");
const u8 gText_F700sQuiz[] = _("{DYNAMIC 0}'s quiz");
const u8 gText_Lady[] = _("Lady");
const u8 gText_AfterYouHaveReadTheQuiz[] = _("Tras leer la pregunta,");
const u8 gText_QuestionPressTheAButton[] = _("pulsa el botón A.");
const u8 gText_TheQuizAnswerIs[] = _("¿La respuesta es?");
const u8 gText_LikeToQuitQuiz[] = _("¿Quieres salir de este cuestionario");
const u8 gText_ChallengeQuestionMark[] = _("desafío?");
const u8 gText_IsThisQuizOK[] = _("¿Está bien este cuestionario?");
const u8 gText_CreateAQuiz[] = _("¡Crea un cuestionario!");
const u8 gText_SelectTheAnswer[] = _("¡Elige la respuesta!");
const u8 gText_LyricsCantBeDeleted[] = _("No se pueden borrar las letras.");
const u8 gText_PokemonLeague[] = _("LIGA POKéMON");
const u8 gText_PokemonCenter[] = _("CENTRO POKéMON");
const u8 gText_GetsAPokeBlockQuestion[] = _(" recibe un {POKEBLOCK}?");
const u8 gText_Coolness[] = _("Carisma ");
const u8 gText_Beauty3[] = _("Belleza ");
const u8 gText_Cuteness[] = _("Dulzura ");
const u8 gText_Smartness[] = _("Ingenio ");
const u8 gText_Toughness[] = _("Dureza ");
const u8 gText_WasEnhanced[] = _("ha aumentado.");
const u8 gText_NothingChanged[] = _("No ha cambiado nada.");
const u8 gText_WontEatAnymore[] = _("Ya no comerá más…");
const u8 gText_SaveFailedCheckingBackup[] = _("Falló el guardado. Comprobando\nla memoria de respaldo…\n{COLOR RED}“Tiempo estimado: 1 minuto”");
const u8 gText_BackupMemoryDamaged[] = _("La memoria de respaldo está dañada\no la pila interna se ha agotado.\nPuedes jugar, pero no guardar.");
const u8 gText_GamePlayCannotBeContinued[] = _("{COLOR RED}“No se puede continuar.\nVolviendo a la pantalla de título…”");
const u8 gText_CheckCompleted[] = _("Comprobación completada.\nIntentando guardar de nuevo.\nEspera un momento.");
const u8 gText_SaveCompleteGameCannotContinue[] = _("Guardado completo.\n{COLOR RED}“No se puede continuar.\nVolviendo a la pantalla de título.”");
const u8 gText_SaveCompletePressA[] = _("Guardado completo.\n{COLOR RED}“Pulsa el botón A.”");
const u8 gText_Ferry[] = _("FERRY");
const u8 gText_SecretBase[] = _("BASE SECRETA");
const u8 gText_Hideout[] = _("GUARIDA");
const u8 gText_ResetRTCConfirmCancel[] = _("¿Reiniciar reloj?\nA: Confirmar, B: Cancelar");
const u8 gText_PresentTime[] = _("Hora actual del juego");
const u8 gText_PreviousTime[] = _("Hora anterior del juego");
const u8 gText_PleaseResetTime[] = _("Reinicia la hora.");
const u8 gText_ClockHasBeenReset[] = _("El reloj se reinició.\nSe guardarán los datos. Espera.");
const u8 gText_SaveCompleted[] = _("Guardado completo.");
const u8 gText_SaveFailed[] = _("Error al guardar…");
const u8 gText_NoSaveFileCantSetTime[] = _("No hay archivo guardado, no se\npuede ajustar la hora.");
const u8 gText_InGameClockUsable[] = _("El ajuste de reloj del juego\nya está disponible.");
const u8 gText_Slots[] = _("TRAGAPERRAS");
const u8 gText_Roulette[] = _("RULETA");
const u8 gText_Good[] = _("Bien");
const u8 gText_VeryGood[] = _("Muy bien");
const u8 gText_Excellent[] = _("Excelente");
const u8 gText_SoSo[] = _("Normal");
const u8 gText_Bad[] = _("Mal");
const u8 gText_TheWorst[] = _("Lo peor");
const u8 gText_Spicy2[] = _("picante");
const u8 gText_Dry2[] = _("seca");
const u8 gText_Sweet2[] = _("dulce");
const u8 gText_Bitter2[] = _("amarga");
const u8 gText_Sour2[] = _("ácida");
const u8 gText_Single[] = _("INDIVIDUAL");
const u8 gText_Double[] = _("DOBLE");
const u8 gText_Jackpot[] = _("bote");
const u8 gText_First[] = _("primero");
const u8 gText_Second[] = _("segundo");
const u8 gText_Third[] = _("tercero");
#if OW_POISON_DAMAGE < GEN_4
const u8 gText_PkmnFainted_FldPsn[] = _("{STR_VAR_1} fainted…\p\n");
#else
const u8 gText_PkmnFainted_FldPsn[] = _("{STR_VAR_1} survived the poisoning.\nThe poison faded away!\p");
#endif
const u8 gText_Marco[] = _("MARCO");
const u8 gText_TrainerCardName[] = _("NAME: ");
const u8 gText_TrainerCardIDNo[] = _("IDNo.");
const u8 gText_TrainerCardMoney[] = _("MONEY");
const u8 gText_PokeDollar[] = _("¥"); // Unused
const u8 gText_TrainerCardPokedex[] = _("POKéDEX");
const u8 gText_EmptyString6[] = _("");
const u8 gText_Colon2[] = _(":");
const u8 gText_Points[] = _(" points"); // Unused
const u8 gText_TrainerCardTime[] = _("TIEMPO");
const u8 gJPText_BattlePoints[] = _("ゲ-ムポイント"); // Unused. Name presumed, translation is Game Points
const u8 gText_Var1sTrainerCard[] = _("TARJETA ENTRENADOR de {STR_VAR_1}");
const u8 gText_HallOfFameDebut[] = _("HALL OF FAME DEBUT  ");
const u8 gText_LinkBattles[] = _("COMBATES ENLACE");
const u8 gText_LinkCableBattles[] = _("COMBATES CABLE");
const u8 gText_WinsLosses[] = _("W:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  L:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}");
const u8 gText_PokemonTrades[] = _("POKéMON TRADES");
const u8 gText_UnionTradesAndBattles[] = _("INTERCAMBIOS Y COMBATES");
const u8 gText_BerryCrush[] = _("MACHACA BAYAS");
const u8 gText_WaitingTrainerFinishReading[] = _("Esperando a que el otro ENTRENADOR\ntermine de leer tu TARJETA ENTRENADOR.");
const u8 gText_PokeblocksWithFriends[] = _("{POKEBLOCK}S C/AMIGOS");
const u8 gText_NumPokeblocks[] = _("{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}");
const u8 gText_WonContestsWFriends[] = _("CONCURSOS GANADOS C/AMIGOS");
const u8 gText_BattlePtsWon[] = _("PUNTOS DE BATALLA GANADOS");
const u8 gText_NumBP[] = _("{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BP");
const u8 gText_BattleTower[] = _("TORRE BATALLA");
const u8 gText_WinsStraight[] = _("W/{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  STRAIGHT/{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}");
const u8 gText_BattleTower2[] = _("TORRE BATALLA");
const u8 gText_BattleDome[] = _("DOMO BATALLA");
const u8 gText_BattlePalace[] = _("PALACIO BATALLA");
const u8 gText_BattleFactory[] = _("FÁBRICA BATALLA");
const u8 gText_BattleArena[] = _("ESTADIO BATALLA");
const u8 gText_BattlePike[] = _("SERPIENTE BATALLA");
const u8 gText_BattlePyramid[] = _("PIRÁMIDE BATALLA");

ALIGNED(4) const u8 gText_FacilitySingle[] = _("{STR_VAR_1} INDIVIDUAL");
ALIGNED(4) const u8 gText_FacilityDouble[] = _("{STR_VAR_1} DOBLE");
ALIGNED(4) const u8 gText_FacilityMulti[] = _("{STR_VAR_1} MULTI");
ALIGNED(4) const u8 gText_FacilityLink[] = _("{STR_VAR_1} ENLACE");
ALIGNED(4) const u8 gText_Facility[] = _("{STR_VAR_1}");

const u8 gText_Give[] = _("Dar");
const u8 gText_NoNeed[] = _("No hace falta");
const u8 gText_ColorLightShadowDarkGray[] = _("{COLOR LIGHT_GRAY}{SHADOW DARK_GRAY}");
const u8 gText_ColorBlue[] = _("{COLOR BLUE}");
const u8 gText_ColorTransparent[] = _("{HIGHLIGHT TRANSPARENT}{COLOR TRANSPARENT}");
const u8 gText_CDot[] = _("C.");
const u8 gText_BDot[] = _("B.");
const u8 gText_AnnouncingResults[] = _("¡Anuncio de resultados!");
const u8 gText_PreliminaryResults[] = _("¡Resultados preliminares!");
const u8 gText_Round2Results[] = _("¡Resultados de la ronda 2!");
const u8 gText_ContestantsMonWon[] = _("{STR_VAR_1} y {STR_VAR_2} ganaron.");
const u8 gText_CommunicationStandby[] = _("En espera de comunicación…");
const u8 gText_ColorDarkGray[] = _("{COLOR DARK_GRAY}");
const u8 gText_ColorDynamic6WhiteDynamic5[] = _("{COLOR_HIGHLIGHT_SHADOW DYNAMIC_COLOR6 WHITE DYNAMIC_COLOR5}"); // Unused
const u8 gText_HealthboxNickname[] = _("{HIGHLIGHT DARK_GRAY}");
const u8 gText_EmptySpace2[] = _(" "); // Unused
const u8 gText_HealthboxGender_Male[] = _("{COLOR DYNAMIC_COLOR2}♂");
const u8 gText_HealthboxGender_Female[] = _("{COLOR DYNAMIC_COLOR1}♀");
const u8 gText_HealthboxGender_None[] = _("{COLOR DYNAMIC_COLOR2}");
const u8 gText_Upper[] = _("SUPERIOR");
const u8 gText_Lower[] = _("inferior");
const u8 gText_Others[] = _("OTROS");
const u8 gText_Symbols[] = _("SÍMBOLOS");
const u8 gText_Register2[] = _("REGISTRAR");
const u8 gText_Exit2[] = _("SALIR");
const u8 gText_QuitChatting[] = _("¿Dejar de chatear?");
const u8 gText_RegisterTextWhere[] = _("¿Registrar texto dónde?");
const u8 gText_RegisterTextHere[] = _("¿Registrar texto aquí?");
const u8 gText_InputText[] = _("Introduce texto.");
const u8 gText_F700JoinedChat[] = _("{DYNAMIC 0} se unió al chat.");
const u8 gText_F700LeftChat[] = _("{DYNAMIC 0} salió del chat.");
const u8 gJPText_PlayersXPokemon[] = _("{DYNAMIC 0}の{DYNAMIC 1}ひきめ:"); // Unused
const u8 gJPText_PlayersXPokmonDoesNotExist[] = _("{DYNAMIC 0}の{DYNAMIC 1}ひきめは いません"); // Unused
const u8 gText_ExitingChat[] = _("Saliendo del chat…");
const u8 gText_LeaderLeftEndingChat[] = _("El LÍDER, {DYNAMIC 0}, ha salido.\nEl chat terminará.");
const u8 gText_RegisteredTextChangedOKToSave[] = _("El texto registrado ha cambiado.\n¿Quieres guardar la partida?");
const u8 gText_AlreadySavedFile_Chat[] = _("Ya hay una partida guardada.\n¿Quieres sobrescribirla?");
const u8 gText_SavingDontTurnOff_Chat[] = _("GUARDANDO…\nNO APAGUES LA CONSOLA.");
const u8 gText_PlayerSavedGame_Chat[] = _("{DYNAMIC 0} guardó la partida.");
const u8 gText_IfLeaderLeavesChatEnds[] = _("Si el LÍDER sale, el chat\nacabará. ¿Está bien?");
const u8 gText_Hello[] = _("HOLA");
const u8 gText_Pokemon2[] = _("POKéMON");
const u8 gText_Trade[] = _("INTERCAMBIO");
const u8 gText_Battle[] = _("COMBATE");
const u8 gText_Lets[] = _("¡VAMOS!");
const u8 gText_Ok[] = _("¡OK!");
const u8 gText_Sorry[] = _("PERDÓN");
const u8 gText_YaySmileEmoji[] = _("¡BIEN!{EMOJI_BIGSMILE}");
const u8 gText_ThankYou[] = _("GRACIAS");
const u8 gText_ByeBye[] = _("¡ADIÓS!");
const u8 gText_PlayerScurriedToCenter[] = _("{PLAYER} corrió al CENTRO POKéMON,\nprotegiendo a los POKéMON agotados y\ndebilitados…\p");
const u8 gText_PlayerScurriedBackHome[] = _("{PLAYER} volvió a casa, protegiendo a\nlos POKéMON agotados y debilitados…\p");
const u8 gText_PlayerRegroupCenter[] = _("{PLAYER} fue al CENTRO POKéMON,\npara reponerse y pensar la estrategia…\p");
const u8 gText_PlayerRegroupHome[] = _("{PLAYER} volvió a casa, para reponerse\ny pensar la estrategia…\p");
const u8 gText_HatchedFromEgg[] = _("¡{STR_VAR_1} salió del HUEVO!");
const u8 gText_NicknameHatchPrompt[] = _("¿Quieres dar mote al recién\nnacido {STR_VAR_1}?");
ALIGNED(4) const u8 gText_ReadyPickBerry[] = _("¿Listo para MACHACA BAYAS?\nElige una BAYA para usar.\p");
ALIGNED(4) const u8 gText_WaitForAllChooseBerry[] = _("Espera mientras cada miembro\nelige una BAYA.");
ALIGNED(4) const u8 gText_EndedWithXUnitsPowder[] = _("{PAUSE_MUSIC}{PLAY_BGM MUS_LEVEL_UP}Obtuviste {STR_VAR_1} unidades de\nPOLVO BAYA muy fino.{RESUME_MUSIC}\pTu cantidad total de POLVO BAYA\nes {STR_VAR_2}.\p");
ALIGNED(4) const u8 gText_RecordingGameResults[] = _("Guardando tus resultados.\lEspera un momento.");
ALIGNED(4) const u8 gText_PlayBerryCrushAgain[] = _("¿Jugar MACHACA BAYAS otra vez?");
ALIGNED(4) const u8 gText_YouHaveNoBerries[] = _("No tienes BAYAS.\nEl juego se cancelará.");
ALIGNED(4) const u8 gText_MemberDroppedOut[] = _("Un miembro se ha desconectado.\nEl juego se cancelará.");
ALIGNED(4) const u8 gText_TimesUpNoGoodPowder[] = _("Se acabó el tiempo.\pNo se pudo obtener buen\nPOLVO BAYA…\p");
ALIGNED(4) const u8 gText_CommunicationStandby2[] = _("En espera de comunicación…");
ALIGNED(4) const u8 gText_1DotBlueF700[] = _("1. {COLOR BLUE}{SHADOW LIGHT_BLUE}{DYNAMIC 0}");
ALIGNED(4) const u8 gText_1DotF700[] = _("1. {DYNAMIC 0}");
ALIGNED(4) const u8 gText_SpaceTimes2[] = _(" vez/veces");
ALIGNED(4) const u8 gText_XDotY[] = _("{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_Var1Berry[] = _("{STR_VAR_1} BAYA");
ALIGNED(4) const u8 gText_TimeColon[] = _("Tiempo:");
ALIGNED(4) const u8 gText_PressingSpeed[] = _("Velocidad:");
ALIGNED(4) const u8 gText_Silkiness[] = _("Suavidad:");
ALIGNED(4) const u8 gText_StrVar1[] = _("{STR_VAR_1}");
ALIGNED(4) const u8 gText_SpaceMin[] = _(" min. ");
ALIGNED(4) const u8 gText_XDotY2[] = _("{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_SpaceSec[] = _(" s.");
ALIGNED(4) const u8 gText_XDotY3[] = _("{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_TimesPerSec[] = _(" veces/seg.");
ALIGNED(4) const u8 gText_Var1Percent[] = _("{STR_VAR_1}%");
ALIGNED(4) const u8 gText_PressesRankings[] = _("Ranking de pulsaciones");
ALIGNED(4) const u8 gText_CrushingResults[] = _("Resultados de machaque");
ALIGNED(4) const u8 gText_NeatnessRankings[] = _("Ranking de precisión");
ALIGNED(4) const u8 gText_CoopRankings[] = _("Ranking cooperativo");
ALIGNED(4) const u8 gText_PressingPowerRankings[] = _("Ranking de potencia");
const u8 gText_BerryCrush2[] = _("MACHACA BAYAS");
const u8 gText_PressingSpeedRankings[] = _("Ranking de velocidad");
const u8 gText_Var1Players[] = _("{STR_VAR_1} JUGADORES");
const u8 gText_SymbolsEarned[] = _("Símbolos conseguidos");
const u8 gText_BattleRecord[] = _("Récord de Combate");
const u8 gText_BattlePoints[] = _("Puntos de Batalla");
const u8 gText_UnusedCancel[] = _("CANCELAR"); // Unused
const u8 gText_EmptyString7[] = _("");
const u8 gText_CheckFrontierMap[] = _("Ver MAPA del FRENTE BATALLA.");
const u8 gText_CheckTrainerCard[] = _("Ver TARJETA ENTRENADOR.");
const u8 gText_ViewRecordedBattle[] = _("Ver combate grabado.");
const u8 gText_PutAwayFrontierPass[] = _("Guardar el PASE FRENTE.");
const u8 gText_CurrentBattlePoints[] = _("Tus Puntos de Batalla actuales.");
const u8 gText_CollectedSymbols[] = _("Tus Símbolos conseguidos.");
const u8 gText_BattleTowerAbilitySymbol[] = _("Torre Batalla - Símbolo de Habilidad");
const u8 gText_BattleDomeTacticsSymbol[] = _("Domo Batalla - Símbolo de Táctica");
const u8 gText_BattlePalaceSpiritsSymbol[] = _("Palacio Batalla - Símbolo de Espíritu");
const u8 gText_BattleArenaGutsSymbol[] = _("Estadio Batalla - Símbolo de Agallas");
const u8 gText_BattleFactoryKnowledgeSymbol[] = _("Fábrica Batalla - Símbolo de Conocimiento");
const u8 gText_BattlePikeLuckSymbol[] = _("Serpiente Batalla - Símbolo de Suerte");
const u8 gText_BattlePyramidBraveSymbol[] = _("Pirámide Batalla - Símbolo de Valentía");
const u8 gText_ThereIsNoBattleRecord[] = _("No hay Récord de Combate.");
const u8 gText_BattleTower3[] = _("TORRE BATALLA");
const u8 gText_BattleDome2[] = _("DOMO BATALLA");
const u8 gText_BattlePalace2[] = _("PALACIO BATALLA");
const u8 gText_BattleArena2[] = _("ESTADIO BATALLA");
const u8 gText_BattleFactory2[] = _("FÁBRICA BATALLA");
const u8 gText_BattlePike2[] = _("SERPIENTE BATALLA");
const u8 gText_BattlePyramid2[] = _("PIRÁMIDE BATALLA");
const u8 gText_BattleTowerDesc[] = _("Derrota rivales y llega a lo más alto.\nTu habilidad será puesta a prueba.");
const u8 gText_BattleDomeDesc[] = _("¡Sigue ganando en el torneo!\nTu táctica será puesta a prueba.");
const u8 gText_BattlePalaceDesc[] = _("¡Mira cómo combate tu POKéMON!\nTu espíritu será puesto a prueba.");
const u8 gText_BattleArenaDesc[] = _("¡Gana combates con tus POKéMON!\nTu valor será puesto a prueba.");
const u8 gText_BattleFactoryDesc[] = _("¡Vence con POKéMON de alquiler!\nTu saber será puesto a prueba.");
const u8 gText_BattlePikeDesc[] = _("¡Elige uno de tres caminos!\nTu suerte será puesta a prueba.");
const u8 gText_BattlePyramidDesc[] = _("¡Explora y llega a lo más alto!\nTu valentía será puesta a prueba.");
const u8 gText_Powder[] = _("POLVO");
const u8 gText_BerryPickingRecords[] = _("RÉCORD RECOGIDA DE BAYAS DODRIO");
const u8 gText_BerriesPicked[] = _("BAYAS recogidas:");
const u8 gText_BestScore[] = _("Mejor marca:");
const u8 gText_BerriesInRowFivePlayers[] = _("BAYAS seguidas con\ncinco jugadores:");
const u8 gText_BerryPickingResults[] = _("¡Anuncio de resultados de recogida!");
const u8 gText_10P30P50P50P[] = _("{CLEAR_TO 0x03}10P{CLEAR_TO 0x2B}30P{CLEAR_TO 0x53}50P{CLEAR_TO 0x77}{EMOJI_MINUS}50P");
const u8 gText_AnnouncingRankings[] = _("¡Anuncio de rankings!");
const u8 gText_AnnouncingPrizes[] = _("¡Anuncio de premios!");
const u8 gText_1Colon[] = _("1:");
const u8 gText_2Colon[] = _("2:");
const u8 gText_3Colon[] = _("3:");
const u8 gText_4Colon[] = _("4:");
const u8 gText_5Colon[] = _("5:");
const u8 gText_FirstPlacePrize[] = _("The first-place winner gets\nthis {DYNAMIC 0}!");
const u8 gText_CantHoldAnyMore[] = _("No puedes llevar más.");
const u8 gText_FilledStorageSpace[] = _("Se llenó el espacio de almacenamiento.");
const u8 gText_WantToPlayAgain[] = _("¿Quieres jugar otra vez?");
const u8 gText_SomeoneDroppedOut[] = _("Alguien se ha desconectado.\nSe cancelará el enlace.");
const u8 gText_SpacePoints[] = _(" puntos");
const u8 gText_CommunicationStandby3[] = _("En espera de comunicación…");
const u8 gText_SpacePoints2[] = _(" puntos");
const u8 gText_SpaceTimes3[] = _(" vez/veces");
const u8 gText_PkmnJumpRecords[] = _("RÉCORD POKéMON SALTO");
const u8 gText_JumpsInARow[] = _("Saltos seguidos:");
const u8 gText_BestScore2[] = _("Mejor marca:");
const u8 gText_ExcellentsInARow[] = _("EXCELENTES seguidos:");
const u8 gText_AwesomeWonF701F700[] = _("¡Gran marca! Has\nganado {DYNAMIC 1} {DYNAMIC 0}!");
const u8 gText_FilledStorageSpace2[] = _("Se llenó el espacio de almacenamiento.");
const u8 gText_CantHoldMore[] = _("No puedes llevar más.");
const u8 gText_WantToPlayAgain2[] = _("¿Quieres jugar otra vez?");
const u8 gText_SomeoneDroppedOut2[] = _("Alguien se ha desconectado.\nSe cancelará el enlace.");
const u8 gText_CommunicationStandby4[] = _("En espera de comunicación…");
const u8 gText_LinkContestResults[] = _("Resultados de Concurso Enlace de {PLAYER}");
const u8 gText_1st[] = _("1.º");
const u8 gText_2nd[] = _("2.º");
const u8 gText_3rd[] = _("3.º");
const u8 gText_4th[] = _("4.º");
const u8 gText_Friend[] = _("Amigo");
const u8 gText_Pokemon3[] = _("POKeMON"); // Unused
const u8 gJPText_MysteryGift[] = _("ふしぎなもらいもの");
const u8 gJPText_DecideStop[] = _("{A_BUTTON}けってい {B_BUTTON}やめる");
const u8 gJPText_ReceiveMysteryGiftWithEReader[] = _("カードeリーダー{PLUS}　で\nふしぎなもらいものを　よみこみます");
const u8 gJPText_SelectConnectFromEReaderMenu[] = _("カードeリーダー{PLUS}の　メニューから\n‘つうしん'を　えらび");
const u8 gJPText_SelectConnectWithGBA[] = _("‘ゲームボーイアドバンスとつうしん'\nを　せんたく　してください");
const u8 gJPText_SelectConnectAndPressA[] = _("カードeリーダー{PLUS}の　‘つうしん'を\nえらんで　Aボタンを　おしてください"); // Unused
const u8 gJPText_LinkIsIncorrect[] = _("せつぞくが　まちがっています");
const u8 gJPText_CardReadingHasBeenHalted[] = _("カードの　よみこみを\nちゅうし　しました");
const u8 gJPText_UnableConnectWithEReader[] = _("カードeリーダー{PLUS}と\nつうしん　できません"); // Unused
const u8 gJPText_Connecting[] = _("つうしん　ちゅう　です");
const u8 gJPText_ConnectionErrorCheckLink[] = _("つうしん　エラーです\nせつぞくを　たしかめて　ください");
const u8 gJPText_ConnectionErrorTryAgain[] = _("つうしん　エラーです\nはじめから　やりなおして　ください"); // Link error
const u8 gJPText_AllowEReaderToLoadCard[] = _("カードeリーダー{PLUS}　に\nカードを　よみこませて　ください");
const u8 gJPText_ConnectionComplete[] = _("つうしん　しゅうりょう！");
const u8 gJPText_NewTrainerHasComeToHoenn[] = _("あらたな　トレーナーが\nホウエンに　やってきた！");
const u8 gJPText_PleaseWaitAMoment[] = _("しばらく　おまちください");
const u8 gJPText_WriteErrorUnableToSaveData[] = _("かきこみ　エラー　です\nデータが　ほぞん　できませんでした");
const u8 gText_SingleBattleRoomResults[] = _("Resultados Sala Individual de {PLAYER}");
const u8 gText_DoubleBattleRoomResults[] = _("Resultados Sala Doble de {PLAYER}");
const u8 gText_MultiBattleRoomResults[] = _("Resultados Sala Múltiple de {PLAYER}");
const u8 gText_LinkMultiBattleRoomResults[] = _("Resultados Sala Múltiple Enlace de {PLAYER}");
const u8 gText_SingleBattleTourneyResults[] = _("Resultados Torneo Individual de {PLAYER}");
const u8 gText_DoubleBattleTourneyResults[] = _("Resultados Torneo Doble de {PLAYER}");
const u8 gText_SingleBattleHallResults[] = _("Resultados Sala Individual de {PLAYER}");
const u8 gText_DoubleBattleHallResults[] = _("Resultados Sala Doble de {PLAYER}");
const u8 gText_BattleChoiceResults[] = _("Resultados Elección de Combate de {PLAYER}");
const u8 gText_SetKOTourneyResults[] = _("Resultados Torneo K.O. de {PLAYER}");
const u8 gText_BattleSwapSingleResults[] = _("Resultados Intercambio Individual de {PLAYER}");
const u8 gText_BattleSwapDoubleResults[] = _("Resultados Intercambio Doble de {PLAYER}");
const u8 gText_BattleQuestResults[] = _("Resultados Misión de Combate de {PLAYER}");
const u8 gText_Lv502[] = _("LV. 50");
const u8 gText_OpenLv[] = _("OPEN LV.");
const u8 gText_WinStreak[] = _("Racha de victorias: {STR_VAR_1}");
const u8 gText_Current[] = _("CURRENT");
const u8 gText_Record[] = _("RÉCORD");
const u8 gText_Prev[] = _("PREV.");
const u8 gText_RentalSwap[] = _("Rental/Swap");
const u8 gText_Total[] = _("Total");
const u8 gText_ClearStreak[] = _("Clear streak: {STR_VAR_1}");
const u8 gText_Championships[] = _("Championships: {STR_VAR_1}");
const u8 gText_RoomsCleared[] = _("Rooms cleared: {STR_VAR_1}");
const u8 gText_TimesCleared[] = _("Times cleared:{CLEAR 0x05}{STR_VAR_1}");
const u8 gText_KOsInARow[] = _("KOs in a row: {STR_VAR_1}");
const u8 gText_TimesVar1[] = _("Times: {STR_VAR_1}");
const u8 gText_FloorsCleared[] = _("Floors cleared: {STR_VAR_1}");

ALIGNED(4) const u8 gText_RecordsLv50[] = _("LV. 50");
ALIGNED(4) const u8 gText_RecordsOpenLevel[] = _("OPEN LEVEL");
ALIGNED(4) const u8 gText_FrontierFacilityWinStreak[] = _("Racha de victorias: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityClearStreak[] = _("Clear streak: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityRoomsCleared[] = _("Rooms cleared: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityKOsStreak[] = _("KOs in a row: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityFloorsCleared[] = _("Floors cleared: {STR_VAR_2}");
ALIGNED(4) const u8 gText_123Dot[][3] = {_("1."), _("2."), _("3.")};
const u8 gText_FrontierFacilityTotalCaughtSpeciesBanned[] = _(" and {STR_VAR_2} of the POKéMON species\nyou caught are inelegible");
const u8 gText_FrontierFacilityIncluding[] = _(".\pThese include ");
const u8 gText_FrontierFacilityAreInelegible[] = _(" are inelegible");

const u8 gText_SavingDontTurnOff2[] = _("GUARDANDO…\nNO APAGUES LA CONSOLA.");
const u8 gText_BlenderMaxSpeedRecord[] = _("MEZCLADOR BAYAS\n¡RÉCORD DE VELOCIDAD!");
const u8 gText_234Players[] = _("2 JUGADORES\n3 JUGADORES\n4 JUGADORES");
const u8 gText_YesNo[] = _("SÍ\nNO");
const u8 gText_SelectorArrow3[] = _("▶");
const u8 gText_Peekaboo[] = _("¡CUCÚ!");
const u8 gText_CommErrorCheckConnections[] = _("Error de comunicación…\nComprueba las conexiones y\napaga y enciende la consola.");
const u8 gText_CommErrorEllipsis[] = _("Error de comunicación…");
const u8 gText_MoveCloserToLinkPartner[] = _("Acércate a tu(s) compañero(s).\nEvita obstáculos entre vosotros.");
const u8 gText_ABtnRegistrationCounter[] = _("Botón A: Registro");
const u8 gText_ABtnTitleScreen[] = _("Botón A: Pantalla título");
const u8 gText_NumPlayerLink[] = _("{STR_VAR_1}P ENLACE");
const u8 gText_BronzeCard[] = _("BRONCE");
const u8 gText_CopperCard[] = _("COBRE");
const u8 gText_SilverCard[] = _("PLATA");
const u8 gText_GoldCard[] = _("ORO");
const u8 gText_Day[] = _("DÍA");
const u8 gText_Colon3[] = _(":");
const u8 gText_Confirm2[] = _("CONFIRMAR");
const u8 gText_Days[] = _("Días"); // Unused
const u8 gText_TimeColon2[] = _("Hora:"); // Unused
const u8 gText_GameTime[] = _("Tiempo de juego"); // Unused
const u8 gText_RTCTime[] = _("Hora RTC"); // Unused
const u8 gText_UpdatedTime[] = _("Hora actualizada"); // Unused
const u8 gText_MenuPokedex[] = _("POKéDEX");
const u8 gText_MenuPokemon[] = _("POKéMON");
const u8 gText_MenuBag[] = _("MOCHILA");
const u8 gText_MenuPokenav[] = _("POKéNAV");
const u8 gText_MenuPlayer[] = _("{PLAYER}");
const u8 gText_MenuSave[] = _("GUARDAR");
const u8 gText_MenuOption[] = _("OPCIONES");
const u8 gText_MenuExit[] = _("SALIR");
const u8 gText_MenuRetire[] = _("RETIRARSE");
const u8 gText_MenuRest[] = _("DESCANSAR");
const u8 gText_MenuDexNav[] = _("DEXNAV");
const u8 gText_SafariBallStock[] = _("SAFARI BALLS\nDisponibles: {STR_VAR_1}");
const u8 gText_BattlePyramidFloor[] = _("Pirámide Batalla\n{STR_VAR_1}");
const u8 gText_Floor1[] = _("Planta 1");
const u8 gText_Floor2[] = _("Planta 2");
const u8 gText_Floor3[] = _("Planta 3");
const u8 gText_Floor4[] = _("Planta 4");
const u8 gText_Floor5[] = _("Planta 5");
const u8 gText_Floor6[] = _("Floor 6");
const u8 gText_Floor7[] = _("Floor 7");
const u8 gText_Peak[] = _("Peak");
const u8 gText_LinkStandby2[] = _("En espera de enlace…\n… … Botón B: Cancelar");
const u8 gText_PressAToLoadEvent[] = _("Pulsa A para cargar el evento.\n… … Botón B: Cancelar");
const u8 gText_LoadingEvent[] = _("Loading event…");
const u8 gText_DontRemoveCableTurnOff[] = _("Don't remove the Game Link cable.\nDon't turn off the power.");
const u8 gText_EventSafelyLoaded[] = _("The event was safely loaded.");
const u8 gText_LoadErrorEndingSession[] = _("Loading error.\nEnding session.");
const u8 gJPText_Player[] = _("プレイヤー"); // Unused
const u8 gJPText_Sama[] = _("さま"); // Unused
const u8 gText_DexHoenn[] = _("HOENN");
const u8 gText_DexNational[] = _("NATIONAL");
const u8 gText_PokedexDiploma[] = _("JUGADOR: {CLEAR 0x10}{COLOR RED}{SHADOW LIGHT_RED}{PLAYER}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}\n\nEste documento certifica\nque has completado con éxito\nla POKéDEX\n{STR_VAR_1}.\n\n{CLEAR_TO 0x42}{COLOR RED}{SHADOW LIGHT_RED}GAME FREAK");
const u8 gJPText_GameFreak[] = _("{COLOR RED}{SHADOW LIGHT_RED}ゲ-ムフリ-ク"); // Unused
const u8 gText_DiplomaEmpty[] = _("{COLOR RED}{SHADOW LIGHT_RED}"); // Unused
const u8 gText_Hoenn[] = _("HOENN");
const u8 gText_OhABite[] = _("Oh! A bite!");
const u8 gText_PokemonOnHook[] = _("A POKéMON's on the hook!");
const u8 gText_NotEvenANibble[] = _("Not even a nibble…{PAUSE_UNTIL_PRESS}");
const u8 gText_ItGotAway[] = _("It got away…{PAUSE_UNTIL_PRESS}");
const u8 gText_XWillBeSentToY[] = _("{STR_VAR_2} will be\nsent to {STR_VAR_1}.");
const u8 gText_ByeByeVar1[] = _("Bye-bye, {STR_VAR_2}!");
const u8 gText_XSentOverY[] = _("{STR_VAR_1} sent over {STR_VAR_3}.");
const u8 gText_TakeGoodCareOfX[] = _("Take good care of {STR_VAR_3}!");

// Easy chat group names
const u8 gEasyChatGroupName_Pokemon[] = _("POKéMON");
const u8 gEasyChatGroupName_Trainer[] = _("TRAINER");
const u8 gEasyChatGroupName_Status[] = _("STATUS");
const u8 gEasyChatGroupName_Battle[] = _("COMBATE");
const u8 gEasyChatGroupName_Greetings[] = _("GREETINGS");
const u8 gEasyChatGroupName_People[] = _("PEOPLE");
const u8 gEasyChatGroupName_Voices[] = _("VOICES");
const u8 gEasyChatGroupName_Speech[] = _("SPEECH");
const u8 gEasyChatGroupName_Endings[] = _("ENDINGS");
const u8 gEasyChatGroupName_Feelings[] = _("FEELINGS");
const u8 gEasyChatGroupName_Conditions[] = _("CONDITIONS");
const u8 gEasyChatGroupName_Actions[] = _("ACTIONS");
const u8 gEasyChatGroupName_Lifestyle[] = _("LIFESTYLE");
const u8 gEasyChatGroupName_Hobbies[] = _("HOBBIES");
const u8 gEasyChatGroupName_Time[] = _("TIEMPO");
const u8 gEasyChatGroupName_Misc[] = _("MISC.");
const u8 gEasyChatGroupName_Adjectives[] = _("ADJECTIVES");
const u8 gEasyChatGroupName_Events[] = _("EVENTS");
const u8 gEasyChatGroupName_Move1[] = _("MOV. 1");
const u8 gEasyChatGroupName_Move2[] = _("MOV. 2");
const u8 gEasyChatGroupName_TrendySaying[] = _("TRENDY SAYING");
const u8 gEasyChatGroupName_Pokemon2[] = _("POKéMON2");

const u8 gText_ThreeQuestionMarks[] = _("???");
const u8 gText_MaxHP[] = _("MAX. HP");
const u8 gText_Attack[] = _("ATTACK");
const u8 gText_Defense[] = _("DEFENSE");
const u8 gText_Speed[] = _("SPEED");
const u8 gText_SpAtk[] = _("SP. ATK");
const u8 gText_SpDef[] = _("SP. DEF");
const u8 gText_Plus[] = _("{PLUS}");
const u8 gText_Dash[] = _("-");
const u8 gText_FromSpace[] = _("From ");
const u8 gText_MixingRecords[] = _("Mixing records…");
const u8 gText_RecordMixingComplete[] = _("Mezcla de récords completada.\nGracias por esperar.");
const u8 gText_YourName[] = _("¿TU NOMBRE?");
const u8 gText_BoxName[] = _("¿NOMBRE DE CAJA?");
const u8 gText_PkmnsNickname[] = _("¿MOTE DE {STR_VAR_1}?");
const u8 gText_TellHimTheWords[] = _("Tell him the words.");
const u8 gText_MoveOkBack[] = _("{DPAD_NONE}MOVER  {A_BUTTON}OK  {B_BUTTON}ATRÁS");
const u8 gText_RentalPkmn2[] = _("POKéMON DE PRÉSTAMO");
const u8 gText_SelectFirstPkmn[] = _("Elige el primer POKéMON.");
const u8 gText_SelectSecondPkmn[] = _("Elige el segundo POKéMON.");
const u8 gText_SelectThirdPkmn[] = _("Elige el tercer POKéMON.");
const u8 gText_Rent[] = _("ALQUILAR");
const u8 gText_Summary[] = _("RESUMEN");
const u8 gText_Others2[] = _("OTROS");
const u8 gText_Deselect[] = _("DESELEC.");
const u8 gText_TheseThreePkmnOkay[] = _("¿Están bien estos tres POKéMON?");
const u8 gText_Yes2[] = _("SÍ");
const u8 gText_No2[] = _("NO");
const u8 gText_CantSelectSamePkmn[] = _("No puedes elegir el mismo {PKMN}.");
const u8 gText_PkmnSwap[] = _("CAMBIO POKéMON");
const u8 gText_SelectPkmnToSwap[] = _("Elige POKéMON para cambiar.");
const u8 gText_SelectPkmnToAccept[] = _("Elige POKéMON para aceptar.");
const u8 gText_Swap[] = _("CAMBIAR");
const u8 gText_Summary2[] = _("RESUMEN");
const u8 gText_Rechoose[] = _("RE-ELEGIR");
const u8 gText_QuitSwapping[] = _("¿Dejar de cambiar?");
const u8 gText_Yes3[] = _("SÍ");
const u8 gText_No3[] = _("NO");
const u8 gText_PkmnForSwap[] = _("{PKMN} PARA CAMBIO");
const u8 gText_Cancel3[] = _("CANCELAR");
const u8 gText_Swap2[] = _("CAMBIAR"); // Unused
const u8 gText_Accept[] = _("ACCEPT"); // Unused
const u8 gText_AcceptThisPkmn[] = _("Accept this POKéMON?");
const u8 gText_4Spaces[] = _("    "); // Unused
const u8 gText_SamePkmnInPartyAlready[] = _("Same {PKMN} in party already.");
const u8 gText_DecimalPoint[] = _(".");
const u8 gText_SavingPlayer[] = _("PLAYER");
const u8 gText_SavingBadges[] = _("BADGES");
const u8 gText_SavingPokedex[] = _("POKéDEX");
const u8 gText_SavingTime[] = _("TIEMPO");
const u8 gText_WirelessCommStatus[] = _("Wireless Communication Status");
const u8 gText_PeopleTrading[] = _("People trading:");
const u8 gText_PeopleBattling[] = _("People battling:");
const u8 gText_PeopleInUnionRoom[] = _("People in the UNION ROOM:");
const u8 gText_PeopleCommunicating[] = _("People communicating:");
const u8 gText_F700Players[] = _("{DYNAMIC 0} players");
const u8 gText_F701Players[] = _("{DYNAMIC 1} players");
const u8 gText_F702Players[] = _("{DYNAMIC 2} players");
const u8 gText_F703Players[] = _("{DYNAMIC 3} players");

const u8 *const gTextTable_Players[] = {
    gText_F700Players,
    gText_F701Players,
    gText_F702Players,
    gText_F703Players
};

ALIGNED(4) const u8 gText_WonderCards[] = _("WONDER CARDS");
ALIGNED(4) const u8 gText_WonderNews[] = _("WONDER NEWS");
ALIGNED(4) const u8 gText_WirelessCommunication[] = _("COMUNICACIÓN INALÁMBRICA");
ALIGNED(4) const u8 gText_Friend2[] = _("FRIEND");
ALIGNED(4) const u8 gText_Exit3[] = _("SALIR");
ALIGNED(4) const u8 gText_Receive[] = _("RECEIVE");
ALIGNED(4) const u8 gText_Send[] = _("SEND");
ALIGNED(4) const u8 gText_Toss[] = _("TOSS");
ALIGNED(4) const u8 gText_VarietyOfEventsImportedWireless[] = _("A variety of events will be imported\nover Wireless Communication.");
ALIGNED(4) const u8 gText_WonderCardsInPossession[] = _("Read the WONDER CARDS in your\npossession.");
ALIGNED(4) const u8 gText_ReadNewsThatArrived[] = _("Read the NEWS that arrived.");
ALIGNED(4) const u8 gText_ReturnToTitle[] = _("Volver a la pantalla de título.");
ALIGNED(4) const u8 gText_DontHaveCardNewOneInput[] = _("You don't have a WONDER CARD,\nso a new CARD will be input.");
ALIGNED(4) const u8 gText_DontHaveNewsNewOneInput[] = _("You don't have any WONDER NEWS,\nso new NEWS will be input.");
ALIGNED(4) const u8 gText_WhereShouldCardBeAccessed[] = _("Where should the WONDER CARD\nbe accessed?");
ALIGNED(4) const u8 gText_WhereShouldNewsBeAccessed[] = _("Where should the WONDER NEWS\nbe accessed?");
ALIGNED(4) const u8 gText_CommunicationStandbyBButtonCancel[] = _("En espera de comunicación…\nBotón B: Cancelar"); // Unused
ALIGNED(4) const u8 gText_Communicating[] = _("Communicating…");
ALIGNED(4) const u8 gText_CommunicationCompleted[] = _("Communication completed.");
ALIGNED(4) const u8 gText_CommunicationError[] = _("Communication error.");
ALIGNED(4) const u8 gText_CommunicationCanceled[] = _("Communication has been canceled.");
ALIGNED(4) const u8 gText_ThrowAwayWonderCard[] = _("¿Tirar la TARJETA MISTERIOSA\ny meter una TARJETA nueva?");
ALIGNED(4) const u8 gText_HaventReceivedCardsGift[] = _("You haven't received the CARD's gift\nyet. Input a new CARD anyway?");
ALIGNED(4) const u8 gText_WonderCardReceivedFrom[] = _("A WONDER CARD has been received\nfrom {STR_VAR_1}.");
ALIGNED(4) const u8 gText_WonderNewsReceivedFrom[] = _("A WONDER NEWS item has been\nreceived from {STR_VAR_1}.");
ALIGNED(4) const u8 gText_WonderCardReceived[] = _("A new WONDER CARD has been\nreceived.");
ALIGNED(4) const u8 gText_WonderNewsReceived[] = _("A new WONDER NEWS item has been\nreceived.");
ALIGNED(4) const u8 gText_NewStampReceived[] = _("A new STAMP has been received.");
ALIGNED(4) const u8 gText_NewTrainerReceived[] = _("A new TRAINER has arrived.");
ALIGNED(4) const u8 gText_AlreadyHadCard[] = _("You already had that\nWONDER CARD.");
ALIGNED(4) const u8 gText_AlreadyHadNews[] = _("You already had that\nWONDER NEWS item.");
ALIGNED(4) const u8 gText_AlreadyHadStamp[] = _("You already had that\nSTAMP.");
ALIGNED(4) const u8 gText_NoMoreRoomForStamps[] = _("There's no more room for adding\nSTAMPS.");
ALIGNED(4) const u8 gText_RecordUploadedViaWireless[] = _("Tu récord se ha subido por\nCOMUNICACIÓN INALÁMBRICA.");
ALIGNED(4) const u8 gText_CantAcceptCardFromTrainer[] = _("No puedes aceptar una TARJETA MISTERIOSA\nde este ENTRENADOR.");
ALIGNED(4) const u8 gText_CantAcceptNewsFromTrainer[] = _("No puedes aceptar NOTICIAS MISTERIOSAS\nde este ENTRENADOR.");
ALIGNED(4) const u8 gText_NothingSentOver[] = _("Nothing was sent over…");
ALIGNED(4) const u8 gText_WhatToDoWithCards[] = _("¿Qué quieres hacer con\nlas TARJETAS MISTERIOSAS?");
ALIGNED(4) const u8 gText_WhatToDoWithNews[] = _("¿Qué quieres hacer con\nlas NOTICIAS MISTERIOSAS?");
ALIGNED(4) const u8 gText_SendingWonderCard[] = _("Sending your WONDER CARD…");
ALIGNED(4) const u8 gText_SendingWonderNews[] = _("Sending your WONDER NEWS item…");
ALIGNED(4) const u8 gText_WonderCardSentTo[] = _("Your WONDER CARD has been sent\nto {STR_VAR_1}.");
ALIGNED(4) const u8 gText_WonderNewsSentTo[] = _("Your WONDER NEWS item has been\nsent to {STR_VAR_1}.");
ALIGNED(4) const u8 gText_StampSentTo[] = _("A STAMP has been sent to {STR_VAR_1}.");
ALIGNED(4) const u8 gText_GiftSentTo[] = _("A GIFT has been sent to {STR_VAR_1}.");
ALIGNED(4) const u8 gText_OtherTrainerHasCard[] = _("The other TRAINER has the same\nWONDER CARD already.");
ALIGNED(4) const u8 gText_OtherTrainerHasNews[] = _("The other TRAINER has the same\nWONDER NEWS already.");
ALIGNED(4) const u8 gText_OtherTrainerHasStamp[] = _("The other TRAINER has the same\nSTAMP already.");
ALIGNED(4) const u8 gText_OtherTrainerCanceled[] = _("The other TRAINER canceled\ncommunication.");
ALIGNED(4) const u8 gText_CantSendGiftToTrainer[] = _("No puedes enviar un REGALO MISTERIOSO\na este ENTRENADOR.");
ALIGNED(4) const u8 gText_IfThrowAwayCardEventWontHappen[] = _("Si tiras la TARJETA,\nel evento no ocurrirá. ¿Vale?");
ALIGNED(4) const u8 gText_OkayToDiscardNews[] = _("Is it okay to discard this\nNEWS item?");
ALIGNED(4) const u8 gText_HaventReceivedGiftOkayToDiscard[] = _("You haven't received the\nGIFT. Is it okay to discard?");
ALIGNED(4) const u8 gText_DataWillBeSaved[] = _("Se guardarán los datos.\nEspera un momento.");
ALIGNED(4) const u8 gText_SaveCompletedPressA[] = _("Guardado completo.\nPulsa el botón A.");
ALIGNED(4) const u8 gText_WonderCardThrownAway[] = _("The WONDER CARD was thrown away.");
ALIGNED(4) const u8 gText_WonderNewsThrownAway[] = _("The WONDER NEWS was thrown away.");
ALIGNED(4) const u8 gText_MysteryGift[] = _("REGALO MISTERIOSO");
ALIGNED(4) const u8 gText_PickOKExit[] = _("{DPAD_UPDOWN}ELIGE {A_BUTTON}OK {B_BUTTON}SALIR");
ALIGNED(4) const u8 gText_PickOKCancel[] = _("{DPAD_UPDOWN}ELIGE {A_BUTTON}OK {B_BUTTON}CANCELAR");
const u8 gText_PlayersBattleResults[] = _("Resultados de combate de {PLAYER}");
const u8 gText_TotalRecordWLD[] = _("RÉCORD TOTAL G:{STR_VAR_1} P:{STR_VAR_2} E:{STR_VAR_3}");
const u8 gText_WinLoseDraw[] = _("{CLEAR_TO 0x53}GANAR{CLEAR_TO 0x80}PERDER{CLEAR_TO 0xB0}EMPATE");
const u8 gText_CommunicationStandby5[] = _("En espera de comunicación…");
const u8 gText_QuitTheGame[] = _("¿Salir del juego?");
const u8 gText_YouveGot9999Coins[] = _("You've got 9,999 COINS.");
const u8 gText_YouveRunOutOfCoins[] = _("You've run out of COINS.\nGame over!");
const u8 gText_YouDontHaveThreeCoins[] = _("You don't have three COINS.");
const u8 gText_ReelTimeHelp[] = _("TIEMPO DE GIRO\n¡Aprovecha para apuntar y\nmarcar puntos!\nDura el número\nde giros otorgados.\nTermina con el Gran Bonus.");
const u8 gDaycareText_GetAlongVeryWell[] = _("The two seem to get along\nvery well.");
const u8 gDaycareText_GetAlong[] = _("The two seem to get along.");
const u8 gDaycareText_DontLikeOther[] = _("The two don't seem to like\neach other much.");
const u8 gDaycareText_PlayOther[] = _("The two prefer to play with other\nPOKéMON than each other.");
const u8 gText_NewLine2[] = _("\n");
const u8 gText_Exit4[] = _("SALIR");
const u8 gText_Lv[] = _("{LV}");
const u8 gText_TimeBoard[] = _("TABLA TIEMPO");
const u8 gText_TimeCleared[] = _("TIEMPO SUPERADO ");
const u8 gText_XMinYDotZSec[] = _("{STR_VAR_1} min. {STR_VAR_2}.{STR_VAR_3} sec.");
const u8 gText_TrainerHill1F[] = _("1F");
const u8 gText_TrainerHill2F[] = _("2F");
const u8 gText_TrainerHill3F[] = _("3F");
const u8 gText_TrainerHill4F[] = _("4F");
const u8 gText_TeachWhichMoveToPkmn[] = _("Teach which {STR_VAR_3} to\n{STR_VAR_1}?");
const u8 gText_MoveRelearnerTeachMoveConfirm[] = _("Teach {STR_VAR_2}?");
const u8 gText_MoveRelearnerPkmnLearnedMove[] = _("{STR_VAR_1} learned\n{STR_VAR_2}!");
const u8 gText_MoveRelearnerPkmnTryingToLearnMove[] = _("{STR_VAR_1} intenta aprender\n{STR_VAR_2}.\pPero {STR_VAR_1} no puede aprender\nmás de cuatro movimientos.\p¿Borras un movimiento para\nhacer sitio a {STR_VAR_2}?");
const u8 gText_MoveRelearnerStopTryingToTeachMove[] = _("Stop trying to teach\n{STR_VAR_2}?");
const u8 gText_MoveRelearnerAndPoof[] = _("{PAUSE 32}1, {PAUSE 15}2, and {PAUSE 15}… {PAUSE 15}… {PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}Poof!\p");
const u8 gText_MoveRelearnerPkmnForgotMoveAndLearnedNew[] = _("{STR_VAR_1} forgot {STR_VAR_3}.\pAnd…\p{STR_VAR_1} learned {STR_VAR_2}.");
const u8 gText_MoveRelearnedPkmnDidNotLearnMove[] = _("{STR_VAR_1} did not learn the\nmove {STR_VAR_2}."); // Unused
const u8 gText_MoveRelearnerGiveUp[] = _("¿Dejar de intentar enseñar un\nmovimiento a {STR_VAR_1}?");
const u8 gText_MoveRelearnerWhichMoveToForget[] = _("Which move should be\nforgotten?\p");
const u8 gText_MoveRelearnerBattleMoves[] = _("MOVIMIENTOS COMBATE");
const u8 gText_MoveRelearnerContestMovesTitle[] = _("MOVS. CONCURSO");
const u8 gText_MoveRelearnerType[] = _("TYPE/"); // Unused
const u8 gText_MoveRelearnerPP[] = _("PP/");
const u8 gText_MoveRelearnerPower[] = _("POWER/");
const u8 gText_MoveRelearnerAccuracy[] = _("ACCURACY/");
const u8 gText_MoveRelearnerAppeal[] = _("APPEAL");
const u8 gText_MoveRelearnerJam[] = _("JAM");
const u8 gText_Kira[] = _("KIRA");
const u8 gText_Amy[] = _("AMY");
const u8 gText_John[] = _("JOHN");
const u8 gText_Roy[] = _("ROY");
const u8 gText_Gabby[] = _("GABBY");
const u8 gText_Anna[] = _("ANNA");
const u8 gText_ClearAllSaveData[] = _("¿Borrar todos los datos guardados?");
const u8 gText_ClearingData[] = _("Clearing data…\nPlease wait.");
const u8 gText_IsThisTheCorrectTime[] = _("Is this the correct time?");
const u8 gText_Confirm3[] = _("CONFIRM");
const u8 gText_Cancel4[] = _("CANCELAR");
const u8 gText_CommStandbyAwaitingOtherPlayer[] = _("En espera de comunicación…\nEsperando a que el otro jugador elija.");
const u8 gText_BattleWasRefused[] = _("The battle was refused.{PAUSE 60}");
const u8 gText_RefusedBattle[] = _("Refused the battle.{PAUSE 60}");
const u8 gText_NoWeather[] = _("SIN CLIMA"); // Below are unused debug names for weather types
const u8 gText_Sunny[] = _("SUNNY"); // Unused
const u8 gText_Sunny2[] = _("SUNNY2"); // Unused
const u8 gText_Rain[] = _("RAIN"); // Unused
const u8 gText_Snow[] = _("SNOW"); // Unused
const u8 gText_Lightning[] = _("LIGHTNING"); // Unused
const u8 gText_Fog[] = _("FOG"); // Unused
const u8 gText_VolcanoAsh[] = _("VOLCANO ASH"); // Unused
const u8 gText_Sandstorm[] = _("SANDSTORM"); // Unused
const u8 gText_Fog2[] = _("FOG2"); // Unused
const u8 gText_Seafloor[] = _("SEAFLOOR"); // Unused
const u8 gText_Cloudy[] = _("CLOUDY"); // Unused
const u8 gText_Sunny3[] = _("SUNNY3"); // Unused
const u8 gText_HeavyRain[] = _("HEAVY RAIN"); // Unused
const u8 gText_Seafloor2[] = _("SEAFLOOR2"); // Unused
const u8 gText_DelAll[] = _("DEL. ALL");
const u8 gText_Cancel5[] = _("CANCELAR");
const u8 gText_Ok2[] = _("OK");
const u8 gText_Quiz[] = _("QUIZ");
const u8 gText_Answer[] = _("ANSWER");
const u8 gText_PokeBalls[] = _("POKé BALLS");
const u8 gText_Berry[] = _("BAYA");
const u8 gText_Berries[] = _("BERRIES");
const u8 gText_ExpShareOn[] = _("The Exp. Share has been turned on.{PAUSE_UNTIL_PRESS}");
const u8 gText_ExpShareOff[] = _("The Exp. Share has been turned off.{PAUSE_UNTIL_PRESS}");
const u8 gText_BasePointsResetToZero[] = _("{STR_VAR_1}'s base points\nwere all reset to zero!{PAUSE_UNTIL_PRESS}");
const u8 gText_AM[] = _("AM");
const u8 gText_PM[] = _("PM");
const u8 gText_Relearn[] = _("{START_BUTTON} RELEARN"); // future note: don't decap this, because it mimics the summary screen BG graphics which will not get decapped
const u8 gText_Relearn_LevelUp[] = _("{START_BUTTON} RELEARN LEVEL");
const u8 gText_Relearn_Egg[] = _("{START_BUTTON} RELEARN EGG");
const u8 gText_Relearn_TM[] = _("{START_BUTTON} RELEARN TM");
const u8 gText_Relearn_Tutor[] = _("{START_BUTTON} RELEARN TUTOR");
const u8 gText_Rename[] = _("RENAME");
const u8 gText_CannotSendMonToBoxHM[] = _("Cannot send that mon to the box,\nbecause it knows a HM move.{PAUSE_UNTIL_PRESS}");
const u8 gText_CannotSendMonToBoxActive[] = _("Cannot send an active battler\nto the box.{PAUSE_UNTIL_PRESS}");
const u8 gText_CannotSendMonToBoxPartner[] = _("Cannot send a mon that doesn't,\nbelong to you to the box.{PAUSE_UNTIL_PRESS}");
